### ISSUE TITLE
machinery analyze does not work on opensuse13.1

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1047]
While working on the yaml file base test selection we triggered analyse tests on opensuse13.1. This however failed as zypper on that system does not support "-x download" as used bye machinery analyze:

--------------------------snip--------------------------
vagrant@linux:~> machinery analyze opensuse131-build --operation=config-file-diffs
Setting up repository access...
Generating diffs...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "zypper --non-interactive --no-gpg-checks --root /tmp/machinery_zypper20150630-6098-iq68d6 -x download cronie-1.4.8" failed with status 2 (no error output).

Standard output:
<?xml version='1.0'?>
<stream>
<message type="error">Unknown command &apos;download&apos;</message>
<message type="info">Type &apos;zypper help&apos; to get a list of global options and commands.</message>
</stream>

Backtrace:
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/logged_cheetah.rb:24:in `block in run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/helper.rb:61:in `with_env'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/helper.rb:51:in `with_c_locale'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/zypper.rb:91:in `block in call_zypper'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/helper.rb:61:in `with_env'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/zypper.rb:90:in `call_zypper'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/zypper.rb:77:in `download_package'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:47:in `block (2 levels) in analyze'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:46:in `each'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:46:in `block in analyze'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:139:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:139:in `block in with_repositories'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/zypper.rb:43:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/zypper.rb:43:in `block in isolated'
/usr/lib64/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/zypper.rb:30:in `isolated'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:106:in `with_repositories'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/analyze_config_file_diffs_task.rb:36:in `analyze'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/lib/cli.rb:253:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bundle/ruby/2.0.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.0.0/gems/machinery-tool-1.9.1.20150630T103230ZopenSUSE131gitb4eaf2a/bin/machinery:28:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
--------------------------snip--------------------------

**Comment by tgoettlicher** [comment]
The `download` command was added to `zypper` in April 2014. That's the reason why it's not available in openSUSE 13.1.

**Comment by cornelius** [comment]
Zypper on openSUSE 13.1 is supposed to have the feature, so we should check, that zypper is up to date on the machine where the problem occurs.

**Comment by vwallfahrer** [comment]
Decided in the daily meeting that it is not necessary to implement it.
