### ISSUE TITLE
comparism of old inpsector with go inspector shows differences

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1137]
Hi, here the diff:

---------------snip----------------
# Unmanaged files

Only in 'old_one':
  * /root/.ssh/ (dir)
  * /usr/lib/mit/ (dir)
  * /usr/share/sip/ (dir)
  * /var/lib/gdm/.ICEauthority (file)
  * /var/lib/gdm/.dbus/ (dir)
  * /var/lib/gdm/.esd_auth (file)
  * /var/lib/gdm/.gconf/ (dir)
  * /var/lib/gdm/.gconfd/ (dir)
  * /var/lib/gdm/.gnome2/ (dir)
  * /var/lib/gdm/.gnome2_private/ (dir)
  * /var/lib/gdm/.gstreamer-0.10/ (dir)
  * /var/lib/gdm/.pulse-cookie (file)
  * /var/lib/gdm/.pulse/ (dir)
  * /var/lib/rpcbind/portmap.xdr (file)
  * /var/lib/rpcbind/rpcbind.xdr (file)
  * /var/lock/dmraid/ (dir)
  * /var/lock/subsys/nfs-rpc.idmapd (file)
  * /var/lock/subsys/syslogd (file)
  * /var/log/Xorg.1.log.old (file)
  * /var/log/Xorg.2.log.old (file)
  * /var/log/Xorg.3.log.old (file)
  * /var/log/Xorg.4.log.old (file)
  * /var/log/Xorg.5.log.old (file)
  * /var/log/boot.omsg (file)
  * /var/log/gdm/:0-slave.log.1 (file)
  * /var/log/gdm/:0-slave.log.2 (file)
  * /var/log/gdm/:0-slave.log.3 (file)
  * /var/log/gdm/:0-slave.log.4 (file)
  * /var/log/gdm/:0.log.1 (file)
  * /var/log/gdm/:0.log.2 (file)
  * /var/log/gdm/:0.log.3 (file)
  * /var/log/gdm/:0.log.4 (file)
  * /var/log/gdm/:1-slave.log.1 (file)
  * /var/log/gdm/:1-slave.log.2 (file)
  * /var/log/gdm/:1-slave.log.3 (file)
  * /var/log/gdm/:1-slave.log.4 (file)
  * /var/log/gdm/:1.log.1 (file)
  * /var/log/gdm/:1.log.2 (file)
  * /var/log/gdm/:1.log.3 (file)
  * /var/log/gdm/:1.log.4 (file)
  * /var/log/gdm/:2-slave.log.1 (file)
  * /var/log/gdm/:2-slave.log.2 (file)
  * /var/log/gdm/:2-slave.log.3 (file)
  * /var/log/gdm/:2-slave.log.4 (file)
  * /var/log/gdm/:2.log.1 (file)
  * /var/log/gdm/:2.log.2 (file)
  * /var/log/gdm/:2.log.3 (file)
  * /var/log/gdm/:2.log.4 (file)
  * /var/log/gdm/:3-slave.log.1 (file)
  * /var/log/gdm/:3-slave.log.2 (file)
  * /var/log/gdm/:3-slave.log.3 (file)
  * /var/log/gdm/:3-slave.log.4 (file)
  * /var/log/gdm/:3.log.1 (file)
  * /var/log/gdm/:3.log.2 (file)
  * /var/log/gdm/:3.log.3 (file)
  * /var/log/gdm/:3.log.4 (file)
  * /var/log/gdm/:4-slave.log.1 (file)
  * /var/log/gdm/:4-slave.log.2 (file)
  * /var/log/gdm/:4-slave.log.3 (file)
  * /var/log/gdm/:4-slave.log.4 (file)
  * /var/log/gdm/:4.log.1 (file)
  * /var/log/gdm/:4.log.2 (file)
  * /var/log/gdm/:4.log.3 (file)
  * /var/log/gdm/:4.log.4 (file)
  * /var/log/gdm/:5-slave.log.1 (file)
  * /var/log/gdm/:5-slave.log.2 (file)
  * /var/log/gdm/:5-slave.log.3 (file)
  * /var/log/gdm/:5-slave.log.4 (file)
  * /var/log/gdm/:5.log.1 (file)
  * /var/log/gdm/:5.log.2 (file)
  * /var/log/gdm/:5.log.3 (file)
  * /var/log/gdm/:5.log.4 (file)
  * /var/log/gdm/::1:1-greeter.log (file)
  * /var/log/gdm/::1:1-slave.log (file)
  * /var/log/xinetd.log (file)
  * /var/log/xvt (file)

Only in 'new_one':
  * /boot/backup_mbr (file)
  * /boot/grub/default (file)
  * /boot/grub/device.map (file)
  * /boot/grub/device.map.old (file)
  * /boot/grub/e2fs_stage1_5 (file)
  * /boot/grub/fat_stage1_5 (file)
  * /boot/grub/ffs_stage1_5 (file)
  * /boot/grub/iso9660_stage1_5 (file)
  * /boot/grub/jfs_stage1_5 (file)
  * /boot/grub/menu.lst (file)
  * /boot/grub/menu.lst.old (file)
  * /boot/grub/minix_stage1_5 (file)
  * /boot/grub/reiserfs_stage1_5 (file)
  * /boot/grub/stage1 (file)
  * /boot/grub/stage2 (file)
  * /boot/grub/ufs2_stage1_5 (file)
  * /boot/grub/vstafs_stage1_5 (file)
  * /boot/grub/xfs_stage1_5 (file)
  * /lib/udev/devices/console (file)
  * /lib/udev/devices/fwmonitor (file)
  * /lib/udev/devices/ippp0 (file)
  * /lib/udev/devices/ippp1 (file)
  * /lib/udev/devices/ippp10 (file)
  * /lib/udev/devices/ippp11 (file)
  * /lib/udev/devices/ippp12 (file)
  * /lib/udev/devices/ippp13 (file)
  * /lib/udev/devices/ippp14 (file)
  * /lib/udev/devices/ippp15 (file)
  * /lib/udev/devices/ippp2 (file)
  * /lib/udev/devices/ippp3 (file)
  * /lib/udev/devices/ippp4 (file)
  * /lib/udev/devices/ippp5 (file)
  * /lib/udev/devices/ippp6 (file)
  * /lib/udev/devices/ippp7 (file)
  * /lib/udev/devices/ippp8 (file)
  * /lib/udev/devices/ippp9 (file)
  * /lib/udev/devices/isdnctrl0 (file)
  * /lib/udev/devices/isdnctrl1 (file)
  * /lib/udev/devices/isdnctrl10 (file)
  * /lib/udev/devices/isdnctrl11 (file)
  * /lib/udev/devices/isdnctrl12 (file)
  * /lib/udev/devices/isdnctrl13 (file)
  * /lib/udev/devices/isdnctrl14 (file)
  * /lib/udev/devices/isdnctrl15 (file)
  * /lib/udev/devices/isdnctrl2 (file)
  * /lib/udev/devices/isdnctrl3 (file)
  * /lib/udev/devices/isdnctrl4 (file)
  * /lib/udev/devices/isdnctrl5 (file)
  * /lib/udev/devices/isdnctrl6 (file)
  * /lib/udev/devices/isdnctrl7 (file)
  * /lib/udev/devices/isdnctrl8 (file)
  * /lib/udev/devices/isdnctrl9 (file)
  * /lib/udev/devices/isdninfo (file)
  * /lib/udev/devices/kmsg (file)
  * /lib/udev/devices/lp0 (file)
  * /lib/udev/devices/md0 (file)
  * /lib/udev/devices/md1 (file)
  * /lib/udev/devices/md10 (file)
  * /lib/udev/devices/md11 (file)
  * /lib/udev/devices/md12 (file)
  * /lib/udev/devices/md13 (file)
  * /lib/udev/devices/md14 (file)
  * /lib/udev/devices/md15 (file)
  * /lib/udev/devices/md16 (file)
  * /lib/udev/devices/md17 (file)
  * /lib/udev/devices/md18 (file)
  * /lib/udev/devices/md19 (file)
  * /lib/udev/devices/md2 (file)
  * /lib/udev/devices/md20 (file)
  * /lib/udev/devices/md21 (file)
  * /lib/udev/devices/md22 (file)
  * /lib/udev/devices/md23 (file)
  * /lib/udev/devices/md24 (file)
  * /lib/udev/devices/md25 (file)
  * /lib/udev/devices/md26 (file)
  * /lib/udev/devices/md27 (file)
  * /lib/udev/devices/md28 (file)
  * /lib/udev/devices/md29 (file)
  * /lib/udev/devices/md3 (file)
  * /lib/udev/devices/md30 (file)
  * /lib/udev/devices/md31 (file)
  * /lib/udev/devices/md4 (file)
  * /lib/udev/devices/md5 (file)
  * /lib/udev/devices/md6 (file)
  * /lib/udev/devices/md7 (file)
  * /lib/udev/devices/md8 (file)
  * /lib/udev/devices/md9 (file)
  * /lib/udev/devices/net/tun (file)
  * /lib/udev/devices/null (file)
  * /lib/udev/devices/ppp (file)
  * /lib/udev/devices/ptmx (file)
  * /lib/udev/devices/route (file)
  * /lib/udev/devices/skip (file)
  * /lib/udev/devices/tty (file)
  * /lib/udev/devices/tty1 (file)
  * /lib/udev/devices/ttyI0 (file)
  * /lib/udev/devices/ttyI1 (file)
  * /lib/udev/devices/ttyI10 (file)
  * /lib/udev/devices/ttyI11 (file)
  * /lib/udev/devices/ttyI12 (file)
  * /lib/udev/devices/ttyI13 (file)
  * /lib/udev/devices/ttyI14 (file)
  * /lib/udev/devices/ttyI15 (file)
  * /lib/udev/devices/ttyI2 (file)
  * /lib/udev/devices/ttyI3 (file)
  * /lib/udev/devices/ttyI4 (file)
  * /lib/udev/devices/ttyI5 (file)
  * /lib/udev/devices/ttyI6 (file)
  * /lib/udev/devices/ttyI7 (file)
  * /lib/udev/devices/ttyI8 (file)
  * /lib/udev/devices/ttyI9 (file)
  * /lib/udev/devices/ttyS0 (file)
  * /lib/udev/devices/ttyS1 (file)
  * /lib/udev/devices/ttyS2 (file)
  * /lib/udev/devices/ttyS3 (file)
  * /lib/udev/devices/ttyS4 (file)
  * /lib/udev/devices/ttyS5 (file)
  * /lib/udev/devices/ttyS6 (file)
  * /lib/udev/devices/ttyS7 (file)
  * /lib/udev/devices/watchdog (file)
  * /lib/udev/devices/zero (file)
  * /var/cache/sax/files/config.new (file)
  * /var/lib/sax/card (file)
  * /var/lib/sax/desktop (file)
  * /var/lib/sax/extensions (file)
  * /var/lib/sax/input (file)
  * /var/lib/sax/keyboard (file)
  * /var/lib/sax/layout (file)
  * /var/lib/sax/path (file)
---------------snip--------------------

Howto reproduce:

- Install a sled11sp3 system 
- Inspect system with old inspector
- Create a copy of the resulting manifest.json
- Inspect system with new go inspector
- Remove unmanaged files section from copy of manifest.json
- Insert the output from the new go inspector in the copy of manifest.json
- run ```machinery compare old new```
=> see diff

**Comment by cornelius** [comment]
The machinery_helper should put out the complete list of unmanaged files and the filtering happens in Ruby. Remote mount points still should be filtered out.

So we check that remote mount are properly excluded, the rest is not relevant anymore.

**Comment by eotchi** [comment]
Fixed
