### ISSUE TITLE
xml files are not shown but only offered for download html view

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1154]
xml files are not shown but only offered for download html view because they are considered binary

**Comment by vwallfahrer** [comment]
I tested it and reported an issue:
https://github.com/minad/mimemagic/issues/27

**Comment by mschnitzer** [comment]
It's definitely an issue from Machinery. That's what I figured out. I'll fix that and open a PR for that.

**Comment by tgoettlicher** [comment]
This issue occurred again at the review meeting.
