### ISSUE TITLE
Issues in HTML view

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1155]
Issues in the HTML view:
* some columns are cut-off and not resizeable 
* checksum is shown in `compare --html` view
* file content view doesn't scroll back to top when a new file is shown

**Comment by eotchi** [comment]
Tracked in 
- https://trello.com/c/YxnQa7qH
- https://trello.com/c/NEMoY85W
- https://trello.com/c/OjlkqoCC

**Comment by mauromorales** [comment]
All issues have been fixed at this point. Couldn't find the PR for the checksum but I've verified that it's in master.

**Comment by tgoettlicher** [comment]
There were layout issues in the users section of the HTML view at the review meeting.

**Comment by cornelius** [comment]
Let's close this and open more specific issues where needed.
