### ISSUE TITLE
Machinery option "-i": unexpected error for unknown IP address

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1186]
The option "-i"/"--ip" will take any input as IP address, and report an enexpected error for bind.

´# machinery show --html --ip p localhost´
There is a web server running, serving the description on http://p:7586/localhost.

The server can be closed with Ctrl+C.

Warning:
You specified an IP address other than '127.0.0.1', your server may be reachable from the network.
This could lead to confidential data like passwords or private keys being readable by others.

Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/2.1.0/socket.rb:232:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
	from /usr/lib64/ruby/2.1.0/socket.rb:232:in `foreach'
	from /usr/lib64/ruby/2.1.0/socket.rb:459:in `tcp_server_sockets'
	from /usr/lib64/ruby/2.1.0/webrick/utils.rb:75:in `create_listeners'
	from /usr/lib64/ruby/2.1.0/webrick/server.rb:132:in `listen'
	from /usr/lib64/ruby/2.1.0/webrick/server.rb:113:in `initialize'
	from /usr/lib64/ruby/2.1.0/webrick/httpserver.rb:45:in `initialize'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/handler/webrick.rb:10:in `new'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/handler/webrick.rb:10:in `run'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1505:in `start_server'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1443:in `run!'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/lib/html.rb:39:in `block in run_server'

´# machinery show --html --ip 10.160.66.253 localhost´
There is a web server running, serving the description on http://10.160.66.253:7586/localhost.

The server can be closed with Ctrl+C.

Warning:
You specified an IP address other than '127.0.0.1', your server may be reachable from the network.
This could lead to confidential data like passwords or private keys being readable by others.

Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/2.1.0/socket.rb:206:in `bind': Cannot assign requested address - bind(2) for 10.160.66.253:7586 (Errno::EADDRNOTAVAIL)
	from /usr/lib64/ruby/2.1.0/socket.rb:206:in `listen'
	from /usr/lib64/ruby/2.1.0/socket.rb:461:in `block in tcp_server_sockets'
	from /usr/lib64/ruby/2.1.0/socket.rb:232:in `each'
	from /usr/lib64/ruby/2.1.0/socket.rb:232:in `foreach'
	from /usr/lib64/ruby/2.1.0/socket.rb:459:in `tcp_server_sockets'
	from /usr/lib64/ruby/2.1.0/webrick/utils.rb:75:in `create_listeners'
	from /usr/lib64/ruby/2.1.0/webrick/server.rb:132:in `listen'
	from /usr/lib64/ruby/2.1.0/webrick/server.rb:113:in `initialize'
	from /usr/lib64/ruby/2.1.0/webrick/httpserver.rb:45:in `initialize'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/handler/webrick.rb:10:in `new'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/handler/webrick.rb:10:in `run'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1505:in `start_server'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1443:in `run!'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.1.20150730T121731ZSLE12git713ed58/lib/html.rb:39:in `block in run_server'

Expected behaviour:
- sane error message for "getaddrinfo: Name or service not known"
- check IP address before starting the web server
- don't start web server if IP check failed

**Comment by mschnitzer** [comment]
WIP
