### ISSUE TITLE
Built-in machinery inspection misses /var/lib/nfs/* directories as unmanaged files

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1250]
Comparing the output of an inspection using machinery-helper to one without (moved helper binary to /tmp) resuslts in the following diff:

´# machinery compare g130-helper g130-wo_helper´
´# Unmanaged files´

Only in 'g130-helper':
  * /var/lib/nfs/rpc_pipefs/cache/ (dir)
  * /var/lib/nfs/rpc_pipefs/lockd/ (dir)
  * /var/lib/nfs/rpc_pipefs/mount/ (dir)
  * /var/lib/nfs/rpc_pipefs/nfs/ (dir)
  * /var/lib/nfs/rpc_pipefs/nfsd4_cb/ (dir)
  * /var/lib/nfs/rpc_pipefs/portmap/ (dir)
  * /var/lib/nfs/rpc_pipefs/statd/ (dir)

Following scopes are identical in both descriptions: os,packages,patterns,repositories,users,groups,services,config_files,changed_managed_files

Since /var/lib/nfs isn't listed as filter, these directories must show up as unmanaged files with the built-in inspection as well.

How to reproduce:
- inspect SLES-11-SP3 64bit system (ensure machinery has /usr/share/machinery/helpers/x86_64/machinery-helper in place)
- (re-)move /usr/share/machinery/helpers/x86_64/machinery-helper for machinery to fall back to built-in inspection
- inspect the same SLES-11-SP3 64bit system
- compare results

**Comment by mauromorales** [comment]
# Operating system [10.161.8.93] (2015-09-10 10:28:44)
    
      Name: SUSE Linux Enterprise Server 11
      Version: 11 SP3
      Architecture: x86_64

Results from doing the comparison after the fix:

    Compared descriptions are identical.
    Following scopes are identical in both descriptions: os,packages,patterns,repositories,users,groups,services,config_files,changed_managed_files,unmanaged_files
