### ISSUE TITLE
inspection of x86_64 from s390 host fails

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1253]
not sure what triggered this, will retry but just filing this for the record in case there is more to it:

--------------------snip------------------
s390vsw144:~ # su - tux
tux@s390vsw144:~> machinery inspect lagrange.suse.de
You are running Machinery on a platform we do not explicitly support and test.
It still could work very well. If you run into issues or would like to provide us feedback, you are welcome to file an issue at https://github.com/SUSE/machinery/issues/new or write an email to machinery@lists.suse.com.
Oficially supported operating systems are: 'SUSE Linux Enterprise Server 12, openSUSE 13.1 (Bottle), openSUSE 13.2 (Harlequin), openSUSE Tumbleweed'

To disable this message in the machinery configuration use 'machinery config perform-support-check=false'
Inspecting lagrange.suse.de for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'openSUSE 13.2 (Harlequin)' version '13.2 (Harlequin)'.
Inspecting packages...
 -> Found 2429 packages.
Inspecting patterns...
 -> Found 47 patterns.
Inspecting repositories...
 -> Found 16 repositories.
Inspecting users...
 -> Found 39 users.
Inspecting groups...
 -> Found 64 groups.
Inspecting services...
 -> Found 215 services.
Inspecting config-files...
 -> Found 24 changed configuration files.
Inspecting changed-managed-files...
 -> Found 199 changed files...Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new                                                                                                                                      
Execution of "ssh root@lagrange.suse.de LC_ALL\=C stat --printf \\\%a:\\\%U:\\\%G:\\\%u:\\\%g:\\\%F:\\\%n\\\\n /usr/lib/virtualbox/VirtualBox /usr/lib64/python3.4/http/__pycache__/__init__.cpython-34.pyc /usr/lib64/python3.4/lib2to3/fixes/__pycache__/__init__.cpython-34.pyc /usr/lib64/browser-plugins/javaplugin.so /usr/lib/virtualbox/VBoxHeadless /usr/lib/virtualbox/VBoxNetAdpCtl /usr/lib/virtualbox/VBoxNetDHCP /usr/lib/virtualbox/VBoxSDL /var/cache/libvirt/qemu /var/lib/libvirt/qemu /usr/lib64/browser-plugins/javaplugin.so /var/lib/PackageKit/transactions.db /usr/share/man/man1/ftp.1.gz /usr/share/java/xml-commons-apis.jar for\\\ shared\\\ lock\\\ on\\\ /var/lib/rpm/Packages /var/cache/cups /usr/bin/X.x11-video-nvidiaG02 /etc/cups /var/lib/libvirt/images /usr/bin/rake.ruby.ruby2.1" failed with status 1: stat: cannot stat 'for shared lock on /var/lib/rpm/Packages': No such file or directory.

Error output:
stat: cannot stat 'for shared lock on /var/lib/rpm/Packages': No such file or directory

Standard output:
4750:root:vboxusers:0:474:regular file:/usr/lib/virtualbox/VirtualBox
644:root:root:0:0:regular file:/usr/lib64/python3.4/http/__pycache__/__init__.cpython-34.pyc
644:root:root:0:0:regular file:/usr/lib64/python3.4/lib2to3/fixes/__pycache__/__init__.cpython-34.pyc
777:root:root:0:0:symbolic link:/usr/lib64/browser-plugins/javaplugin.so
4750:root:vboxusers:0:474:regular file:/usr/lib/virtualbox/VBoxHeadless
4750:root:vboxusers:0:474:regular file:/usr/lib/virtualbox/VBoxNetAdpCtl
4750:root:vboxusers:0:474:regular file:/usr/lib/virtualbox/VBoxNetDHCP
4750:root:vboxusers:0:474:regular file:/usr/lib/virtualbox/VBoxSDL
750:chuller:qemu:10562:486:directory:/var/cache/libvirt/qemu
750:chuller:qemu:10562:486:directory:/var/lib/libvirt/qemu
777:root:root:0:0:symbolic link:/usr/lib64/browser-plugins/javaplugin.so
644:root:root:0:0:regular file:/var/lib/PackageKit/transactions.db
777:root:root:0:0:symbolic link:/usr/share/man/man1/ftp.1.gz
777:root:root:0:0:symbolic link:/usr/share/java/xml-commons-apis.jar
775:root:lp:0:7:directory:/var/cache/cups
755:root:root:0:0:regular file:/usr/bin/X.x11-video-nvidiaG02
755:root:lp:0:7:directory:/etc/cups
777:root:root:0:0:symbolic link:/var/lib/libvirt/images
755:root:root:0:0:regular file:/usr/bin/rake.ruby.ruby2.1

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/logged_cheetah.rb:24:in `block in run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/helper.rb:61:in `with_env'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/helper.rb:51:in `with_c_locale'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/remote_system.rb:77:in `run_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/changed_rpm_files_helper.rb:108:in `get_file_properties'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/changed_rpm_files_helper.rb:139:in `get_path_data'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/changed_managed_files/changed_managed_files_inspector.rb:74:in `amend_file_attributes'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/changed_managed_files/changed_managed_files_inspector.rb:138:in `changed_files'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/changed_managed_files/changed_managed_files_inspector.rb:37:in `inspect'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:86:in `block in build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:78:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:78:in `build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:23:in `inspect_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/cli.rb:538:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bin/machinery:28:in `<top (required)>'
/usr/bin/machinery:24:in `load'
/usr/bin/machinery:24:in `<main>'
--------------------snip------------------

**Comment by cornelius** [comment]
On what system was this tested? The output says that Machinery is running on an unsupported system. Was this a SLES 12?

**Comment by greygoo** [comment]
The machine was provided from the QA pool, but seems to be not on the latest service pack:

---------------snip--------------
s390vsw144:~ # cat /etc/SuSE-release 
SUSE Linux Enterprise Server 12 (s390x)
VERSION = 12
PATCHLEVEL = 1
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
---------------snip--------------

I was focused on the error trace and did oversee the 'unsupported' message.

**Comment by thardeck** [comment]
I think this is a race condition which occurs when files get removed during inspection.

**Comment by cornelius** [comment]
#2188 will fix this
