### ISSUE TITLE
export-autoyast option fails when target has no repositories.

### ISSUE THREAD

**Issue by scotsman2k** [SUSE/machinery#1268]
![image](https://cloud.githubusercontent.com/assets/5496907/9589082/f8fdea8e-4ff9-11e5-95f3-97fdae4ae7a0.png)

**Comment by greygoo** [comment]
QA:

When I inspect a system which has no repos set up, I can do an export:
-------------------------------snip---------------------------------
chuller@lagrange:/data/big/chuller/machinery(master)> ./bin/machinery --debug export-autoyast no_repos_2_sle11_removed --autoyast-dir /tmp

Unmanaged files following these patterns are not exported:
var/lib/rpm/*
etc/passwd*
etc/shadow*
etc/group*
etc/fstab
lib/mkinitrd
etc/udev/rules.d/70-persistent-net.rules
var/log/*
etc/default/grub*
etc/zypp/repos.d/*


Note: The permssions of the AutoYaST directory are restricted to be only accessible by the current user. Further instructions are provided by the README.md in the exported directory.
Exported to '/tmp/no_repos_2_sle11_removed-autoyast'.
-------------------------------snip---------------------------------

However, when skippig the repo inspection altogether, an error message prevents me from exporting to autoyast:

---------------------------------snip-----------------------------------
chuller@lagrange:/data/big/chuller/machinery(master)> ./bin/machinery --debug export-autoyast no_repos_2_sle11 --autoyast-dir /tmp
The system description misses the following scope : repositories.
---------------------------------snip-----------------------------------

Is this the intended behaviour?
