### ISSUE TITLE
Kiwi export not comaptible with SUSEStudio

### ISSUE THREAD

**Issue by coogor** [SUSE/machinery#1301]
Morning all,
I heard on the oSC 2015 about machinery and its ability to create a Kiwi-Export, which can be used as the basis for an Studio-Build. However, import to Studio fails with the error message: 
 could not find 'Source' directory 
Not sure where the source of the problem is, but in the Studio Forum nobody could help.

**Comment by thardeck** [comment]
Hi, thx for the report. The reason for this is that SUSE Studio expects a `source` directory in the tarball, where the configuration and the root directory is stored inside.

But even when I move everything to a source directory and compress it with tar.gz the import fails with "Invalid sequence in interleave Invalid sequence in interleave Element image failed to validate content". I will look into it.

**Comment by thardeck** [comment]
The issue seems to be related to Studio, I will forward the issue.

**Comment by ChrisBr** [comment]
We adapted the Studio import like stated in this Fate: https://fate.suse.com/318388
Not sure how the machinery export looks like, however, we stick now to structure stated in this fate...

**Comment by coogor** [comment]
Sorry, this page is not public to openSUSE users, and it is not on openFATE.
Did you align both projects somehow?

**Comment by thardeck** [comment]
The kiwi configuration exchange format is: 

- a tar ball compressed with xz.
- it contains a "config.xml" at top level. This is a required file.
- further optional files, like image.sh, config.sh and alike are packaged as well on top level
- all layered files are inside of the directory called "root/" inside of this archive
- the file name suffix of this archive should be .kiwi.txz

But I have tried compressing our export and uploading it to Susestudio and had an issue which is currently looked at. I will let you know as soon as there are some news.

**Comment by thardeck** [comment]
Hey, to give you a heads up, we are still working on this. We have improved our Kiwi export and there is already a Studio development version which can import at least the packages.

**Comment by cornelius** [comment]
Is this still an issue?

We will support the Kiwi standard export format which should resolve any remaining problems. #2190

**Comment by coogor** [comment]
Yes, still an issue. KIWI from studio behaves different than on OBS than on local build. Machinery I haven't tried. But just taking the sources from lets say Studio and drop it to OBS does not work....
