### ISSUE TITLE
Make installation instructions on home page more friendly for non SUSE users

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1360]
The installation instructions on the Machinery home page are very much biased towards SUSE distributions. To reach more possible users it would help to make them more friendly to users of non-SUSE systems.

Related to that we might want to think about providing packages for other distributions as well.

**Comment by mauromorales** [comment]
We still don't have packages but the home page now points to https://github.com/SUSE/machinery/wiki/Installation-on-Other-Distributions

I'm assuming we can close but feel free to re open
