### ISSUE TITLE
Separate user and developer documentation

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1372]
There is some mix between documentation targeted at users and developers of Machinery itself. It would be clearer, if they would be clearly separated.

I would suggest to do the following to fix that:

* [x] Put all documentation targeted at developers of Machinery itself into the [docs directory](https://github.com/SUSE/machinery/tree/master/docs) in the machinery git repository. So developers have everything available in one place when they check out the git repo.
* [x] Add a table of content to the [README.md](https://github.com/SUSE/machinery/blob/master/docs/README.md) in the docs directory giving an overview and some structure to the documentation.
* [x] Remove information only targeted at people who already are developers of Machinery from the Machinery Wiki. Keep the information about how to make the transition from user to developer. Also keep the information for developers working with Machinery, but not on Machinery.

**Comment by greygoo** [comment]
QA PASSED
