### ISSUE TITLE
Clearly link documentation from README.md

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1374]
The [Machinery README](https://github.com/SUSE/machinery/blob/master/README.md) should have clear links to documentation. It should link the end user documentation (the rendered man page) (and not link to the sources of the man page like it is doing now), and it should link the developer documentation (the docs directory).

I would suggest to adapt the structure of the README a little bit, so that it has the following sections:

* Installation
* Usage
* Documentation
* Development
* Contact

**Comment by greygoo** [comment]
QA PASSED
