### ISSUE TITLE
Better representation of user documentation

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1376]
The Machinery user documentation is currently presented as man page. It is installed with the command line tool and [rendered on the home page](http://machinery-project.org/manual.html).

While this is the traditional path for command line tools, it has a number of limitations. The structure of the man page is pretty much flat, with sections, but without hierarchy. There is no good navigation such as a table of contents or links between sections or to other material. The formatting is limited by the conventions of man pages and the tool used to render the man page has a couple of issues.

I think we should move to a better representation of our user documentation. It should not be driven by the choice of technology, but by what serves users best. The standard is nicely formatted documentation on the web now. There are some good examples (e.g. [Docker](http://docs.docker.com/), [Vagrant](https://docs.vagrantup.com/), [SUSE Studio](https://susestudio.com/help/), [GitHub](https://help.github.com/)).

The work flow for creating documentation (write a simple format such as Markdown, maintain the documentation in git, render it to what is needed) makes sense, though. We should keep this in some form.

**Comment by mauromorales** [comment]
Docker seems to be using [mkdocs](http://www.mkdocs.org/)

 - markdown
 - It looks nice out of the box
 - Customizable (bootstrap, fontawesome, etc)

Seems like a good candidate to me ;)

**Comment by mauromorales** [comment]
Would this card be fulfilled now that we've moved to mkdocs?

**Comment by cornelius** [comment]
Done: http://machinery-project.org/docs/
