### ISSUE TITLE
Misleading/no error output for inspecting systems with "No space left on device"

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1388]
While again btrfs/snapper related, I inspected a SLES-11-SP3 system where system-root has "No space left on device" - ("df" reports 60% Used).

Machinery fails at the stage of "Inspecting unmanaged-files", but reports:
"rm: cannot remove `/root/machinery-helper': No such file or directory."
which is misleading, at least is just the consequence of the original issue.

Machinery also fails to log the error output for:
"# scp /usr/share/machinery/helpers/x86_64/machinery-helper root@hawk:/root"
scp: /root/machinery-helper: No space left on device

Inspection failing:
'# machinery inspect -n hawk1 hawk'
Inspecting hawk for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...
...
Inspecting unmanaged-files...
Note: Using helper binary for inspection of unmanaged files.
 -> Inspection failed!
Errors while inspecting unmanaged-files:
 -> Could not remove file '/root/machinery-helper' on host 'hawk'.
Error: Execution of "ssh root@hawk -o LogLevel\=ERROR LC_ALL\=en_US.utf8 rm /root/machinery-helper" failed with status 1: rm: cannot remove `/root/machinery-helper': No such file or directory.

Log snippet:
I, [2015-09-18T19:08:12.795061 #6362]  INFO -- : Running 'scp /usr/share/machinery/helpers/x86_64/machinery-helper root@hawk:/root'
I, [2015-09-18T19:08:12.940893 #6362]  INFO -- : Running 'ssh root@hawk -o LogLevel=ERROR LC_ALL=en_US.utf8 rm /root/machinery-helper'
E, [2015-09-18T19:08:13.075638 #6362] ERROR -- : Errors while inspecting unmanaged-files:
 -> Could not remove file '/root/machinery-helper' on host 'hawk'.
Error: Execution of "ssh root@hawk -o LogLevel\=ERROR LC_ALL\=en_US.utf8 rm /root/machinery-helper" failed with status 1: rm: cannot remove `/root/machinery-helper': No such file or directory.

So:
1. scp of machinery-helper to inspected system fails silently
2. remote execution of machinery-helper fails silently

**Comment by mauromorales** [comment]
Couldn't find a card so I removed the "tracked by SUSE" tag

**Comment by fschueller** [comment]
If the system runs out of disk space, there could be so many issues that can lead to failures so it's not practicable to implement checks for all of these.
