### ISSUE TITLE
When containerizing a wordpress system, no setup.rb exists

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1407]
According to the README file in the output-dir of containerize, the user is supposed to run `./setup.rb` in that directory. That fails however as no setup.rb exists:

----------------------snip-------------------------
chuller@lagrange:/data/big/chuller/container/wordpress> cat README.md 
# README for Docker Containers created by Machinery

...

Once installed please make sure to run the setup script before running
`docker-compose up`.

    ./setup.rb

...

chuller@lagrange:/data/big/chuller/container/wordpress> ./setup.rb
bash: ./setup.rb: No such file or directory
chuller@lagrange:/data/big/chuller/container/wordpress> ls
docker-compose.yml  mariadb  README.md  wordpress
----------------------snip-------------------------

**Comment by mauromorales** [comment]
@greygoo Right now we mention in the README that we include this script only when it's necessary. Would this be good enough? I don't think we want to make this dynamic for the time being but if there is a better way to express it I'll be glad to improve it.

    When necessary, we've included a `setup.rb` script

**Comment by mauromorales** [comment]
ended up adding a setup.rb to avoid the problem of the connection with the db
