### ISSUE TITLE
in compare --html: when collapsing all scopes - the "both" link is still visible but does not work anymore

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1469]
Howto reproduce:

o run `machinery compare --html system1 system2`
=> see a browser displaying the differences and common items
o click on 'collapse all'
=> see all scopes collapse their content
=> see each scope still have a 'both' link beside them
o click the 'both' link
=> nothing happens

**Comment by mschnitzer** [comment]
Confirmed. I'll work on that.
