### ISSUE TITLE
Piping `machinery help` makes machinery crash

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1496]
Crashes: ``$ ./bin/machinery help | head``
Doesn't crash: ``$ ./bin/machinery --help | head``

```
$ ./bin/machinery help | head
NAME
    machinery - A systems management toolkit for Linux

SYNOPSIS
    machinery [global options] command [command options] [arguments...]

VERSION
    1.14.1 (system description format version 5)

GLOBAL OPTIONS
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/data/machinery/lib/hint.rb:43:in ``': Broken pipe (Errno::EPIPE)
        from /data/machinery/lib/hint.rb:43:in `which_machinery'
        from /data/machinery/lib/hint.rb:33:in `program_name'
        from /data/machinery/lib/hint.rb:47:in `get_started'
        from /data/machinery/lib/hint.rb:29:in `to_string'
        from /data/machinery/lib/hint.rb:23:in `print'
        from /data/machinery/lib/cli.rb:59:in `block in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:313:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:313:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.2/lib/gli/app_support.rb:83:in `run'
        from ./bin/machinery:34:in `<main>'
```

**Comment by mschnitzer** [comment]
@tgoettlicher I cannot reproduce this. It works fine for me.

**Comment by mauromorales** [comment]
can reproduce with machinery 1.18.0

**Comment by promulo** [comment]
I can also reproduce this with 1.18.0 for both cases, `help` and `--help`

If you use `grep` though, it does not crash:

`[promulo@siren machinery]$ ./bin/machinery --help | grep machinery`
`    machinery - A systems management toolkit for Linux`
`    machinery [global options] command [command options] [arguments...]`
`    config            - Show or change machinery's configuration`
`For more detailed information, open the documentation by typing 'machinery man --html'.`
`at https://github.com/SUSE/machinery/wiki`
`These hints can be switched off by './bin/machinery config hints=off'.`
`'./bin/machinery inspect HOSTNAME'`
`'./bin/machinery inspect --remote-user USER HOSTNAME'`

**Comment by promulo** [comment]
Hi @tgoettlicher and @mauromorales, I have created a PR for this bug. Feel free to take a look.

https://github.com/SUSE/machinery/pull/2023

Hope it helps. :)

Paulo
