### ISSUE TITLE
There is an empty alert shown in the HTML comparison

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1508]
See screenshot:

![rendered1](https://cloud.githubusercontent.com/assets/23799/10541710/857ce5a4-7413-11e5-8d06-d770dec9ca79.png)

It's comparing two descriptions which each hav a package, repositories, and an extracted unmanaged files scope.

**Comment by aduffeck** [comment]
@cornelius can you please provide the two descriptions you used there somewhere?

**Comment by cornelius** [comment]
@aduffeck I copied them to my Export.
