### ISSUE TITLE
Machinery Error

### ISSUE THREAD

**Issue by cpwitbooi** [SUSE/machinery#1526]
```
Inspecting unmanaged-files...
 -> Extracted 876 files and treesMachinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/unmanaged_files/unmanaged_files_inspector.rb:101:in `block (2 levels) in extract_tar_metadata': undefined method `user=' for nil:NilClass (NoMethodError)
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/unmanaged_files/unmanaged_files_inspector.rb:96:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/unmanaged_files/unmanaged_files_inspector.rb:96:in `block in extract_tar_metadata'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/unmanaged_files/unmanaged_files_inspector.rb:93:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/unmanaged_files/unmanaged_files_inspector.rb:93:in `extract_tar_metadata'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/plugins/unmanaged_files/unmanaged_files_inspector.rb:360:in `inspect'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:86:in `block in build_description'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:78:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:78:in `build_description'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/inspect_task.rb:23:in `inspect_system'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/lib/cli.rb:538:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.11.2/bin/machinery:28:in `<top (required)>'
        from /usr/bin/machinery:24:in `load'
        from /usr/bin/machinery:24:in `<main>'
```

**Comment by mauromorales** [comment]
Hi @cpwitbooi, 

Thanks for reporting the issue,

Would you mind giving us a few steps on how to reproduce the issue?
 - Command you were running
 - Distro you were running machinery from
 - System you were inspecting

**Comment by cpwitbooi** [comment]
Hi mauromorales

Sorry I meant to post some more detail.

- Command I was running
machinery inspect --extract-files --scope=unmanaged-files HOST

- Distro I'm running machinery from
 SUSE Linux Enterprise Server 12 (x86_64) 

- System I'm inspecting 
SUSE Linux Enterprise Server 11.3 (x86_64)

**Comment by mauromorales** [comment]
@cpwitbooi we started a release process for SLES so you will be able to update to the latest version very soon which should solve this issue. I'll ping you again as soon as it's out.

**Comment by cpwitbooi** [comment]
mauromorales just to be clear is this a new release of machinery?

**Comment by mauromorales** [comment]
@cpwitbooi yes this one will be version 1.14

**Comment by mauromorales** [comment]
@cpwitbooi the latest version is available for download. Could you update and give it another shot and see if your issue is solved? Weather it does or it doesn't keep me posted so I can follow up with you.

Cheers,

**Comment by cpwitbooi** [comment]
Awesome thanks, will it be available via repositories?

**Comment by mauromorales** [comment]
@cpwitbooi yup it should be accessible from [SLE-12:Update](https://build.suse.de/package/show/SUSE:SLE-12:Update/machinery)

**Comment by cpwitbooi** [comment]
Hi 

I get the following message when doing an inspection using machinery. "Note: Using traditional inspection because there is no helper binary for architecture 'x86_64' available." 

Does any know what the helper binary is for architecture 'x86_64?

Regards

**Comment by mauromorales** [comment]
@cpwitbooi are you trying to inspect from an x64 system to an x64 system? right now that's the only scenario where we support the machinery-helper

**Comment by cpwitbooi** [comment]
@mauromorales yes i am trying to inspect from x64 to x64, in my scenario mentioned above there is no helper binary is there a specific package or program i have to install to get the helper binary?

**Comment by mauromorales** [comment]
@cpwitbooi in my case if I do an `rpm -ql machinery` it lists it under `/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.1/machinery-helper/machinery-helper` (I'm using leap but I guess it should be pretty close to sles right? ^__^ ) can you also double check if it lists the helper for you?

**Comment by cpwitbooi** [comment]
@mauromorales it does list the helper under the same path as yours, so why does it tell me that there is no helper binary?

**Comment by mschnitzer** [comment]
@cpwitbooi I'd like to reproduce it. Would you please so kind giving me more information? Are you still trying to inspect a SUSE Linux Enterprise Server 11.3 system from SUSE Linux Enterprise Server 12? Are you using the development setup of Machinery (from GitHub) or did you install it via zypper from a repository?

**Comment by mschnitzer** [comment]
I tried it (inspecting SLES11SP3 from a SLES12) machine and I didn't get that notice. Can you maybe just type `rpm -ql machinery | grep helper` and paste the output here?

**Comment by cpwitbooi** [comment]
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/test/option_test_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/gli-2.11.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers/action_view_extensions.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers/action_view_mods.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers/action_view_xss_mods.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers/safe_erubis_template.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/lib/haml/helpers/xss_mods.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/test/helper_test.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/test/results/helpers.xhtml
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/test/templates/_text_area_helper.html.haml
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/test/templates/helpers.haml
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/haml-4.0.5/test/test_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/nokogiri-1.6.1/test/helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/rack-protection-1.5.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/sinatra-1.4.6/test/helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/sinatra-1.4.6/test/helpers_test.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/sinatra-1.4.6/test/integration_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/bundle/ruby/2.1.0/gems/tilt-2.0.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers/autoyast_export_readme.md
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers/containerize_readme.md
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers/kiwi_export_readme.md
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers/merge_users_and_groups.pl.erb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers/unmanaged_files_autoyast_excludes
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/export_helpers/unmanaged_files_kiwi_excludes
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/inspect_helpers
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/inspect_helpers/changed_files.sh
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/inspect_helpers/yum_repositories.py
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/changed_rpm_files_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/machinery_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/lib/renderer_helper.rb
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/README.md
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/Rakefile
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/machinery-helper
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/machinery_helper.go
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/machinery_helper_test.go
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/mountpoints.go
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/mountpoints_test.go
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/tar.go
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/machinery-helper/version.go
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.14.2/tools/helper_builder.rb

**Comment by mschnitzer** [comment]
Interesting... I have exactly the same files in the directories. When did you start using machinery? (Approximately)

It would be nice to know which version you installed first. It's not a problem if you can't remember, though.

**Comment by cpwitbooi** [comment]
its the version just before the one i have installed now

**Comment by cpwitbooi** [comment]
i think it might be because i installed machinery from the repositories and when i updated i downloaded from github

**Comment by mauromorales** [comment]
@cpwitbooi yes if you downloaded it from github you need to make sure the go binary was built. You should also be able to just install it as a gem and get the machinery-helper from there.

**Comment by mauromorales** [comment]
@cpwitbooi asumming this is not an issue anymore. If it is just write back and I'll follow up with you.
