### ISSUE TITLE
HTML View Crashes if Config File Diff contains '\ No newline at end of file'

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1576]
The HTML view crashes if a config file diff contains the line `\ No newline at end of file`.

For example:
```
--- a/etc/tuned/active_profile
+++ b/etc/tuned/active_profile
@@ -0,0 +1 @@
+balanced
\ No newline at end of file
```

**Comment by tgoettlicher** [comment]
The reason is probably `diff_to_object` not handling the last line properly:
https://github.com/SUSE/machinery/blob/master/lib/server.rb#L140

**Comment by mauromorales** [comment]
Cannot reproduce in machinery 1.18.0 ... will close for now and we can reopen if the issue re appears.
