### ISSUE TITLE
Inspection without default SSH port

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1587]
During the inspection of one of my servers I figured out, that it's not possible to inspect a machine without the default SSH port. I already started working on it and will open a PR in the near feature (when I have time to continue working on it).

My solution: Add an option to set the SSH port. If that option is not set, use port 22.

Branch: https://github.com/SUSE/machinery/tree/inspect_ssh_port

**Comment by mauromorales** [comment]
@mschnitzer you can always just add a rule to your `.ssh/config` to tell it which is the default port you want to connect to.

**Comment by tigerfoot** [comment]
@mauromorales not really usefull if you have 50 hosts with one port 50 with another one etc etc ...
port should be a simple option at run time.
@mschnitzer Any progress on your branch

**Comment by mschnitzer** [comment]
@tigerfoot sorry for the delayed answer. No there is currently no progress from my side. @mauromorales did we agree on a solution?

**Comment by mschnitzer** [comment]
@tigerfoot I talked with @mauromorales and we decided to implement that. I will continue working on it.

**Comment by tigerfoot** [comment]
Thanks for the follow up. If you need whatever tests, feel free to ask

**Comment by mauromorales** [comment]
@tigerfoot you will see this feature in Machinery 1.17 which is just being released. Please test it out and share your feedback. Thanks!

**Comment by tigerfoot** [comment]
Sorry I've forgot to bring feedback : it simply work as expected !!!
Great enhancement. Thank you all.

**Comment by mauromorales** [comment]
@tigerfoot no worries, glad we could help :smile: and thanks for your feedback!
