### ISSUE TITLE
Error during unmanaged-files inspection with special characters in file names

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1596]
If we inspect a system with a folder called `\\t\\t\\`, we get an exception because `tar` has a problem to find this folder. I provided a fix for that but it's really dirty.

My fix: https://github.com/SUSE/machinery/commit/d9c2e75451ef8a095d161d3241bff170dfd17996#diff-0b982cec396a79b74c4a0743b2d1a0c2R80

Before I give an array with all files to the `stdin` stream, I look for backslashes in a file name and add another backslash in front of the other backslash. I do that to escape backslashes. I tried to use the `shellwords` include (which is by default part in the Ruby library) but it turned out that it's not a solution since `shellwords` escapes (for whatever reason) the percent character twice. When I pass then the files to the `stdin` stream, the `\\t\\t\\t` problem is solved but another error occurred with files containing a `%` character in their file name. I didn't find a good solution and I wrote my own function for that (this is currently not in an own method because it was just a test if it would work at all). It looks like that the problem is solved with my dirty hack but I'm still not fine with it and I would like to see some other suggestions because as I said, it's really dirty.

**Comment by mauromorales** [comment]
@mschnitzer do you know what's the status on this?

**Comment by mauromorales** [comment]
I think I found the related PR #1596
