### ISSUE TITLE
raise InspectionFailed "Yum repository baseurl is missing. Metalinks are not supported at the moment."  centos system

### ISSUE THREAD

**Issue by zhailibao2013** [SUSE/machinery#1610]
when test in centos system,
.
Errors while inspecting repositories:
 -> Yum repository baseurl is missing. Metalinks are not supported at the moment.

some yum repository not contain baseurl,but mirrorlist

**Comment by mauromorales** [comment]
Hi @zhailibao2013 

Unfortunately we don't support CentOS just yet so I can't promise we'll get this fixed. Nevertheless if you help me out following up on this issue I'll be happy to look into it. 

Could you send me the CentOS version you are using and if possible how your yum repositories look like. Feel free to change any URL you don't want to make public, I just need to see an example so I can try to replicate locally.

Cheers,

**Comment by zhailibao2013** [comment]
thanks for your replay.
my centos version is 7.my yum repo file like this

# CentOS-Base.repo
#
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for CentOS updates
# unless you are manually picking other mirrors.
#
# If the mirrorlist= does not work for you, as a fall back you can try the 
# remarked out baseurl= line instead.
#
#
[base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&
infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#released updates 
[updates]
...............


please support mirrorlist，not only baseurl in yum repository
