### ISSUE TITLE
Machinery Error when inspecting

### ISSUE THREAD

**Issue by cpwitbooi** [SUSE/machinery#1611]
Hi 

I receive the following error when running the following command machinery inspect --extract-files $HOSTNAME

 -> Extracted 1992 files and treesError: No space left on device @ io_write - /root/.machinery/$HOSTNAME/unmanaged_files.tmp/trees/sybase.tgz

**Comment by mauromorales** [comment]
@cpwitbooi looks to me like machinery has no more space to write the extracted files inside `/root/.machinery` could you double check by doing something like `df -kh /root`

**Comment by mauromorales** [comment]
@cpwitbooi I'm going to close this issue but if by any chance it was something different feel free to re open or ping me so we can follow up ;)

**Comment by cpwitbooi** [comment]
No problem go ahead


Kind Regards

Chad-Lee Witbooi

Linux Technical Support


OptiSolutions (Pty) Ltd

Head Office: 6th Floor, 36-on-Long , 36 Long Street, Cape Town, 8001, South Africa.Landline: +2721 824 4016
Fax: +27 86 600 8887Midrand Office: 10 Wessels Road, Rivonia, Sandton, Johannesburg, 2128, South AfricaLandline: +2711 234 1660Mobile: +2771 241 2901www.optisolutions.co.za


----- Original Message -----From: Mauro Morales <notifications@github.com>To: SUSE/machinery <machinery@noreply.github.com>Cc: cpwitbooi <cpwitbooi@optisolutions.co.za>Sent: Mon, 16 Nov 2015 10:00:17 +0200 (SAST)Subject: Re: [machinery] Machinery Error when inspecting (#1611)

@cpwitbooi I'm going to close this issue but if by any chance it was something different feel free to re open or ping me so we can follow up ;)
&mdash;Reply to this email directly or view it on GitHub.
