### ISSUE TITLE
Comparing the same system descriptions shows obsolete message

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#1613]
When comparing the same system descriptions it shows the following message.
```
Compared descriptions are identical.
Following scopes are identical in both descriptions: os,packages,patterns,repositories,users,groups,services,config_files,changed_managed_files,unmanaged_files
```
The first line is enough, the second is not needed if they are identical.

**Comment by mschnitzer** [comment]
There is an empty line left.
```
Compared descriptions are identical.

lines 1-2/2 (END)
```

Besides that, it looks good to me. (change log entry is missing)
