### ISSUE TITLE
`export-autoyast` does not support openSUSE Leap

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1627]
`machinery export-autoyast` does not support openSUSE Leap.

**Comment by paco-cruz-iesbelen** [comment]
After reading [this openSUSE news](https://news.opensuse.org/2015/11/12/tumbleweed-gets-firefox-42-machinery-ready-for-leap/) I have just updated machinery from the systemsmanagement repo, and the result is:
```
leapserver:~ # machinery export-autoyast leap_base –autoyast-dir=/tmp/my_migration
Export of operating system ‘openSUSE Leap 42.1 42.1 (x86_64)’ is not supported.
```
