### ISSUE TITLE
Tooltip of warning message in html view is misleading

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1629]
Tooltip of warning message in html view is misleading. It says `collapse/expand` but actually closes the message.

![tooltip](https://cloud.githubusercontent.com/assets/1260116/11068816/7331659a-87d3-11e5-970b-2f6c8c72b756.png)

**Comment by fschueller** [comment]
I believe this was fixed in https://github.com/SUSE/machinery/pull/1917
