### ISSUE TITLE
Machinery suggests to copy an SSH key to an invalid IP address

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1635]
When an invalid IP address is specified in the CLI (e.g. 255.255.255.255), Machinery wants the user to copy his SSH-Key to that remote host. Regardless whether the IP address is correct or not.

Maybe an explicit message like "The network is unreachable" does make more sense BEFORE trying to ssh-copy-id a key to the remote host.

**Comment by thardeck** [comment]
I don't think machinery should need checks like this. If the user provides unreachables hostnames or ips there is not much we can do about it either so why add the logic about ip structure?

**Comment by mauromorales** [comment]
Agree with @thardeck specially because this also involves domain names.

Closing for now
