### ISSUE TITLE
Duplicate of #1627: machinery export-autoyast fails in Leap 42.1 

### ISSUE THREAD

**Issue by paco-cruz-iesbelen** [SUSE/machinery#1644]
After reading [this openSUSE news](https://news.opensuse.org/2015/11/12/tumbleweed-gets-firefox-42-machinery-ready-for-leap/) I have just updated machinery from the systemsmanagement repo, and the result is:

```
leapserver:~ # machinery export-autoyast leap_base –autoyast-dir=/tmp/my_migration
Export of operating system ‘openSUSE Leap 42.1 42.1 (x86_64)’ is not supported.
```

**Comment by paco-cruz-iesbelen** [comment]
I am sorry, just found that this issue is a dup of  [#1627: `export-autoyast` does not support openSUSE Leap](https://github.com/SUSE/machinery/issues/1627)

Don`t know how to delete this. :-(

**Comment by mauromorales** [comment]
Hi @paco-cruz-iesbelen thanks for referencing to the previous issue.

Closing
