### ISSUE TITLE
Fails to run under Ubuntu 14.04.03

### ISSUE THREAD

**Issue by thsundel** [SUSE/machinery#1645]
Hi,
I saw this tool presented at SUSECon 2015 and thought it could be useful in our environment, I've tried it on SUSE and it works nicely but when I try to inspect Ubuntu it fails (followed the install instructions documented), I have a vague memory that the presenters said that it is not yet supported on other distros than SLE/RHEL so maybe that is why it fails to inspect my Ubuntu machine?

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

sudo machinery inspect --name UBUNTU localhost
/var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/lib/machinery.rb:103:in `require_relative': /var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/lib/server.rb:113: invalid multibyte char (US-ASCII) (SyntaxError)
/var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/lib/server.rb:113: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/lib/server.rb:113: syntax error, unexpected $end, expecting ')'
...te(change[0], attribute) + " ↔ " +
...                               ^
	from /var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/lib/machinery.rb:103:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/bin/machinery:20:in `require_relative'
	from /var/lib/gems/1.9.1/gems/machinery-tool-1.16.1/bin/machinery:20:in `<top (required)>'
	from /usr/local/bin/machinery:23:in `load'
	from /usr/local/bin/machinery:23:in `<main>'

**Comment by mauromorales** [comment]
Hi @thsundel thanks for reaching out. Yes at the moment most of the functionality will only work for SLE/RHEL however we are on the process of making this features work in Ubuntu as well. If our plan goes as expected we should have a release in the next 3-4 weeks. I can keep you posted and it would be great if you could help us test that everything works as expected.

**Comment by thsundel** [comment]
Great, I'll give it a testdrive when the new release arrives. Any plans to deliver it through OBS as deb repo at some point?

**Comment by mauromorales** [comment]
@thsundel yup but couldn't tell you how soon, probably until it's stable ^__^

**Comment by mauromorales** [comment]
@thsundel just to keep you on the loop. We integrated Ubuntu into our testing environment during our last sprint and will take this sprint to include the missing functionality to inspect Ubuntu systems. I'll write back once you can give it a shot.

**Comment by thardeck** [comment]
We have now added support for Ubuntu 14.04 inspection to master, but we haven't released a new package yet.

**Comment by mauromorales** [comment]
@thsundel please test Machinery 1.17 if you get a chance. Looking forward to get some feedback from you.

**Comment by thsundel** [comment]
I'll test it, is there a deb available or do I need to go the ruby gem way?

**Comment by mauromorales** [comment]
@thsundel No deb yet so with the gem
