### ISSUE TITLE
Count of Inspected Ubuntu Services Differs from System

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1717]
While the inspection of Ubuntu 14.04 LTS services finisged successful, there is a difference between services found and insstalled.
While for an Ubuntu Desktop machinery listed 100 Services, the running system lists 104 services with "initctl list".
Furthermore the system is running "apparmor", but this service isn't listed by machinery and/or "initctl list" at all - it's shown by e.g. "service --status-all".
So we will need to figure out how to reliably list all services on Ubuntu.

**Comment by greygoo** [comment]
the issue with the differing numbers seems to come from different ways to show some of the services. 
the list from show-config:
  /sbin/initctl show-config -e | grep -e "^[[:alpha:]]" | sort
the list from list
  /sbin/initctl list | awk '{print $1}' | sort

If the output is diffed it shows that the additional services in the list view are simply services that are repeatedly listed like e.g. the network-interface service which is listed for each available network interface. 

For apparmor on the other hand we have to extend the inspector to also track services that are invisible in upstart tools, we might need another service section listing them as sysV services or we ignore them for now.

**Comment by greygoo** [comment]
it is possible to see apparmor and other services with ```service --status-all```
However, that lists some more than just apparmor - but still less than initctl. Should we also evaluate the outpu of this command and then sync the list of services with the srvice list obtained from initctl?
I can do that but wonder if this is not rather a bug in ubuntu and if we should really work around that at this point.

**Comment by greygoo** [comment]
I compared the output of ```services --status--all``` with the output of ```initctl list```

So far on the minimal ubuntu system used for pennyworth these services listed with ```services --status--all``` do not appear in the initctl output:

```
for i in `service --status-all 2>&1 | awk '{print $4}'`; do grep $i /tmp/initctl.list > /dev/null || echo $i; done
apparmor
dns-clean
grub-common
killprocs
ntp
ondemand
pppd-dns
rc.local
rsync
sendsigs
sudo
umountfs
umountnfs.sh
umountroot
urandom
```

I doubt we can say that this is a bug in ubuntu and just ignore it.

**Comment by thardeck** [comment]
This should also be fixed
