### ISSUE TITLE
Missing Link from System Descriptions back to Landing Page

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1747]
When testing the new machinery landing page (machinery serve) I can easily navigate to existing system descriptions by clicking on their link - however, if I'm watching a system description, there's no link to the landing page present.
The user needs to use the browsers navigation buttons, or to modify the URL - a link would be more intuitive.
Also, if you "show --html" or "serve" a specific description, the landing page can be accessed just by modifying the URL to the html server root - without a link to the server root/landing page nobody will be aware of that.
Off course such links would need to support current server IP and Port.

**Comment by fschueller** [comment]
Fixed in version 1.21.0
