### ISSUE TITLE
Document Landing Page

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1749]
Document that a plain "machinery serve" (landing page) will now work.
A plain "machinery serve" will start a web server for the http server root (landing page):

'# machinery serve'
Trying to start a web server for serving all system descriptions on http://127.0.0.1:7585/

The web server can be closed with Ctrl+C.

This, and any other way to start the server's document root should be evaluated and documented in the man page - e.g. a plain "machinery show" currently doesn't work.

Now that I also tested the "list" command, it's also not documented that it can take the --html option.

**Comment by greygoo** [comment]
Fixed
