### ISSUE TITLE
Landing Page fails with incompatible system description format

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1762]
While 'machinery list' will list all available descriptions, and put warnings for incompatible formats, the landing page ('machinery list --html') will just fail to show anything even with just one incompatible description - but showing the following error:

"Machinery::Errors::SystemDescriptionIncompatible at /
The system description 'swallow' has an incompatible data format and can not be read. Try 'machinery upgrade-format swallow' to upgrade it to the current version."

**Comment by greygoo** [comment]
Fixed
