### ISSUE TITLE
Landing Page shows wrong suggestion for newer system description format

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1763]
While 'machinery list' shows the correct suggestions for dealing with incompatible system description formats (machinery supports version 5, present descriptions are 4,  5 and 6):

'''# machinery list
 format4-test: format version 4, needs to be upgraded.

 format5-test:
   * os

 format6-test: format version 6. Please upgrade Machinery to the latest version.

Hint: To upgrade all system descriptions run:
machinery upgrade-format --all'''

... 'machinery list --html' will not only fail to list the descriptions, and error out, but also suggests try upgrading the future format version - which is wrong:

Machinery::Errors::SystemDescriptionIncompatible at /
The system description 'format6-test' has an incompatible data format and can not be read. Try 'machinery upgrade-format format6-test' to upgrade it to the current version.

Just like with 'machinery list' system descriptions on the landing page should be listed, while
- compatible descriptions should show up/be accessible
- suggesting to 'machinery upgrade-format <older version>'
- machinery needs to be upgraded in order to access newer description format

**Comment by greygoo** [comment]
Fixed
