### ISSUE TITLE
Machinery reports "Patterns are not supported on this system" on ubuntu systems, when package "tasksel" isn't installed

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1777]
> machinery inspect -s os,patterns -n ubuntu-patterns e42
Inspecting e42 for os, patterns...
Inspecting os...
 -> Found operating system 'Ubuntu 14.04.3 LTS' version '14.04.3 LTS, Trusty Tahr'.
Inspecting patterns...
 -> Patterns are not supported on this system.

In fact the package tasksel wasn't installed with a default Ubuntu desktop. Installing tasksel on the target system then made machinery list 3 tasks/patterns for the very same system.

"Patterns are not supported on this system." is misleading.
We should return a more sane message for ubuntu systems missing tasksel.

**Comment by mauromorales** [comment]
The check is now in place so I will close this issue. We should definitely rephrase to something that makes sense depending on the distro but we can track that on #1820
