### ISSUE TITLE
Support non default ssh keys

### ISSUE THREAD

**Issue by rjschwei** [SUSE/machinery#1803]
machinery should provide an option to pass the location of an ssh key to use to connect to remote hosts.

At present only the default key of the user of the machinery command is used. This may not be the appropriate key to use. Especially in Public Cloud settings where users often have different keys for different machine settings. Having an option on the command line that tells machinery which key to use for a given host would greatly simplify the use of machinery with remote hosts.

**Comment by mauromorales** [comment]
relates to #1587

**Comment by mauromorales** [comment]
@rjschwei would adding the additional keys to your authentication agent and to your ssh config file solve this problem for you?

adding:

    $ ssh-add ~/.ssh/id_rsa_A
    $ ssh-add ~/.ssh/id_rsa_B

config:

    #~/.ssh/config
    Host A.example.com
        HostName example.com
        User A
        IdentityFile ~/.ssh/id_rsa_A

    Host B.example.com
        HostName github.com
        User B
        IdentityFile ~/.ssh/id_rsa_B

**Comment by mauromorales** [comment]
@rjschwei we've added the feature, please test it out and would be great if we can get some feedback on that or anything else.

Also thanks a lot for writing the blog post that was mint :+1:
