### ISSUE TITLE
Config-files in HTML view are misaligned

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#1814]
The config-files in the HTML view is misaligned.

**Comment by mschnitzer** [comment]
Same for me. Tested with master: https://github.com/SUSE/machinery/tree/b9de8bcf08f921bd1af2818a3e7f02fe738a0eeb

![screenshot-2](https://cloud.githubusercontent.com/assets/8287131/12441540/50d0d8d0-bf48-11e5-87ed-c58c2c1a0dd4.png)
