### ISSUE TITLE
fedora18 inspection crashes

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1880]
Inspecting a fedora18 system triggers a crash:

-------------------------------------------snip---------------------------------------------------
chuller@lagrange:/data/chuller/machinery(master)> ./bin/machinery inspect 192.168.122.53
Inspecting 192.168.122.53 for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'Fedora 18 (Spherical Cow)' version '18 (Spherical Cow)'.
Inspecting packages...
 -> Found 937 packages.
Inspecting patterns...
 -> Patterns are not supported on this system.
Inspecting repositories...
 -> Found 9 repositories.
Inspecting users...
 -> Found 33 users.
Inspecting groups...
 -> Found 51 groups.
Inspecting services...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh root@192.168.122.53 -o LogLevel\=ERROR LANGUAGE\= LC_ALL\=en_US.utf8 systemctl list-unit-files --type\\\=service,socket" failed with status 1: Unkown unit type or load state 'service,socket'..

Error output:
Unkown unit type or load state 'service,socket'.

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/data/chuller/machinery/lib/logged_cheetah.rb:23:in `run'
/data/chuller/machinery/lib/remote_system.rb:84:in `run_command'
/data/chuller/machinery/plugins/services/services_inspector.rb:54:in `inspect_systemd_services'
/data/chuller/machinery/plugins/services/services_inspector.rb:32:in `inspect'
/data/chuller/machinery/lib/inspect_task.rb:87:in `block in build_description'
/data/chuller/machinery/lib/inspect_task.rb:79:in `each'
/data/chuller/machinery/lib/inspect_task.rb:79:in `build_description'
/data/chuller/machinery/lib/inspect_task.rb:21:in `inspect_system'
/data/chuller/machinery/lib/cli.rb:595:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
./bin/machinery:33:in `<main>'
-------------------------------------------snip---------------------------------------------------

**Comment by thardeck** [comment]
Fedora 18 is not supported by its vendor anymore so I am not sure if it is worth to add exceptions for it to our service inspector.

**Comment by greygoo** [comment]
i think we can close this then.

**Comment by mschnitzer** [comment]
Closed as discussed.
