### ISSUE TITLE
analyzing a RHEL6 system description fails with an exception

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1890]
just tried to run analyze on a rhel6 system description and it breaks machinery:

------------------------------snip---------------------------------------
chuller@lagrange:/data/chuller/machinery(master)> ./bin/machinery inspect -x 192.168.121.230
Inspecting 192.168.121.230 for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'Red Hat Enterprise Linux Server' version '6.5 (Santiago)'.
Inspecting packages...
 -> Found 479 packages.
Inspecting patterns...
 -> Patterns are not supported on this system.
Inspecting repositories...
 -> Found 3 repositories.
Inspecting users...
 -> Found 27 users.
Inspecting groups...
 -> Found 54 groups.
Inspecting services...
 -> Found 40 services.
Inspecting config-files...
 -> Extracted 13 changed configuration files.
Inspecting changed-managed-files...
 -> Extracted 26 changed files.
Inspecting unmanaged-files...
/usr/local/broken�filename contains invalid UTF-8 characters. Skipping.
 -> Extracted 542 unmanaged files and trees.

Hint: To show the data of the system you just inspected run:
./bin/machinery show 192.168.121.230

chuller@lagrange:/data/chuller/machinery(master)> ./bin/machinery analyze 192.168.121.230
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/data/chuller/machinery/plugins/repositories/repositories_model.rb:21:in `external_medium?': undefined method `start_with?' for #<Array:0x00000004273018> (NoMethodError)
        from /data/chuller/machinery/lib/analyze_config_file_diffs_task.rb:28:in `block in analyze'
        from /data/chuller/machinery/lib/array.rb:187:in `each'
        from /data/chuller/machinery/lib/array.rb:187:in `any?'
        from /data/chuller/machinery/lib/array.rb:187:in `method_missing'
        from /data/chuller/machinery/lib/analyze_config_file_diffs_task.rb:28:in `analyze'
        from /data/chuller/machinery/lib/cli.rb:288:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
        from ./bin/machinery:33:in `<main>'
------------------------------snip---------------------------------------

**Comment by fschueller** [comment]
Fixed in commit 1962b2f51cb3efbc7114f81bf6abe3d443cd85a8
