### ISSUE TITLE
remote user inspection of ubuntu system fails for files inspections

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1893]
I inspected a ubuntu desktop system with remote user called tux after adding the line mentioned in the man page to /etc/sudoers: 

tux ALL=(ALL) NOPASSWD: /usr/bin/find,/usr/bin/cat,/bin/cat,/usr/bin/rsync,/bin/rpm -Va *,/bin/tar --create *

The I ran an inspection of the system as the user tux and ran into errors for the file inspection:

------------------------snip------------------------------
chuller@lagrange:/data/chuller/machinery(master)> ./bin/machinery inspect -x -r tux  192.168.122.205
Inspecting 192.168.122.205 for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'Ubuntu 14.04.1 LTS' version '14.04.1 LTS, Trusty Tahr'.
Inspecting packages...
 -> Found 2204 packages.
Inspecting patterns...
 -> Found 9 patterns.
Inspecting repositories...
 -> Found 5 repositories.
Inspecting users...
 -> Found 42 users.
Inspecting groups...
 -> Found 70 groups.
Inspecting services...
 -> Found 140 services.
Inspecting config-files...
Warning: The list of changed config and managed files is not complete on dpkg systems. The reason for this is missing verifcation data: https://github.com/SUSE/machinery/wiki/Ubuntu-Inspection
 -> Inspection failed!
Inspecting changed-managed-files...
Warning: The list of changed config and managed files is not complete on dpkg systems. The reason for this is missing verifcation data: https://github.com/SUSE/machinery/wiki/Ubuntu-Inspection
 -> Inspection failed!
Inspecting unmanaged-files...
Note: Using traditional inspection because there is no helper binary for architecture 'i686' available.
 -> Inspection failed!

Errors while inspecting config-files:
 -> sudo isn't configured on the inspected host '192.168.122.205' for user 'tux' to give all required commands enough privileges. See 'PREREQUISITES' secton in the machinery man page for a description on how to configure sudo on the inspected host.

Errors while inspecting changed-managed-files:
 -> sudo isn't configured on the inspected host '192.168.122.205' for user 'tux' to give all required commands enough privileges. See 'PREREQUISITES' secton in the machinery man page for a description on how to configure sudo on the inspected host.

Errors while inspecting unmanaged-files:
 -> sudo isn't configured on the inspected host '192.168.122.205' for user 'tux' to give all required commands enough privileges. See 'PREREQUISITES' secton in the machinery man page for a description on how to configure sudo on the inspected host.
------------------------snip------------------------------

**Comment by thardeck** [comment]
It looks like you used the sudoers line for rpm and not dpkg from the man page.

```
    * On dpkg based systems, like Debian or Ubuntu:

      machinery ALL=(ALL) NOPASSWD: /usr/bin/find,/usr/bin/cat,/bin/cat,/usr/bin/rsync,/bin/tar --create *,/usr/bin/stat,/usr/bin/dpkg,/bin/readlink
```

**Comment by greygoo** [comment]
confirmed to work with correct sudoers line
