### ISSUE TITLE
machinery inspect localhost

### ISSUE THREAD

**Issue by dineamix** [SUSE/machinery#1897]
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "rpm -qf /usr/X11R6/lib/libGL.la\ \(replaced\)" failed with status 1: error: file /usr/X11R6/lib/libGL.la (replaced): No such file or directory.

**Comment by mschnitzer** [comment]
Hi,

thanks for reporting a bug. What distribution did you install?

**Comment by dineamix** [comment]
Hi Manuel,

OpenSuse 13.2 x64 . All updates Applied.  Desktop bundles include KDE, 
Gnome, Cinnamon,  LKDE and Mate.

**Comment by mschnitzer** [comment]
OK, thanks. I'll work on that as soon as possible. When this issue is closed, you can expect your fix in the next release of Machinery.

**Comment by aduffeck** [comment]
@dineamix I failed to reproduce this issue. Can you maybe paste the rest of the error message (esp. the part after `Backtrace:`) and attach the output of `rpm -qaV` (run as root)? Thanks.

**Comment by mschnitzer** [comment]
@dineamix Could you also please execute `machinery --version` and paste the output here? And please don't forget the backtrace as @aduffeck mentioned.

**Comment by mschnitzer** [comment]
@aduffeck and I priovided a fix for it. It should be fixed in the next release of Machinery. Please reopen this issue, when the bug appears again.

**Comment by mschnitzer** [comment]
@dineamix the fix is included in Machinery 1.18.0
