### ISSUE TITLE
HTML view doesn't show file meta data

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1902]
The HTML view doesn't show the information about if the files are extracted or, if they are, any meta data. This makes it pretty hard to find information in the HTML view, when looking for where interesting files could be. The output on the console shows it, but it's hard to search.

What I was looking for is a place where a significant amount of unmanaged files were stored. The place turned out to be `/opt` with a content of 500 MB of data, but that wasn't possible to tell in the HTML view.

**Comment by fschueller** [comment]
As long as metadata is extracted the information is available in the HTML view, so the issue has been fixed.
