### ISSUE TITLE
Encryption of extracted data

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1919]
While I was writing the guide about the security, an idea came into my mind. How about encrypting data what we extract during the inspection? For example: The user can enter a password what should be used to encrypt the data. When the user wants to show, serve, or compare data, it has to enter the password what was used for the encryption.

**Comment by mauromorales** [comment]
@mschnitzer will you follow up with this?

**Comment by mschnitzer** [comment]
@mauromorales as discussed in IRC: I won't work on that since I changed the team. For this we need a discussion with the team to plan what we want to achieve with that and how we implement it. I'd love to work on that but there is to less time for this. Hopefully this gets implemented by someone else.

**Comment by thardeck** [comment]
I do not think that we need to reinvent the wheel, it can easily be achieved by [eCryptfs](http://ecryptfs.org/).

Closing as discussed in the daily.
