### ISSUE TITLE
Exception for "machinery show <description with newer format version>"

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1926]
On Leap:
'''# rpm -q machinery
machinery-1.16.4-6.1.x86_64'''

'''# machinery list
 sles-full: format version 6. Please upgrade Machinery to the latest version.'''

... show will return unexpected error for descriptions with future format version.

'''# machinery show --html sles-full
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/json_validator.rb:61:in `read': No such file or directory @ rb_sysopen - /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/schema/system-description-global.schema-v6.json (Errno::ENOENT)
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/json_validator.rb:61:in `global_schema'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/json_validator.rb:30:in `initialize'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/manifest.rb:46:in `new'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/manifest.rb:46:in `validate'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/system_description.rb:65:in `load'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/lib/cli.rb:781:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.16.4/bin/machinery:33:in `<top (required)>'
	from /usr/bin/machinery:24:in `load'
	from /usr/bin/machinery:24:in `<main>''''

while older format-versions are still handled correctly:
'''# machinery show filter-test
filter-test: format version 3, needs to be upgraded. Try 'machinery upgrade-format filter-test' to upgrade it to the current version.'''

**Comment by greygoo** [comment]
fixed for ```machinery show --html $description_with_old_format_version```

However, running   
```machinery serve```  and then connecting to ```http://127.0.0.1:7585/$description_with_old_format_version```
still runs into an exception.
