### ISSUE TITLE
machinery serve with an old format version triggers exception

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1940]
Running   
```machinery serve```

and then connecting to

``` http://127.0.0.1:7585/$description_with_old_format_version ```

 runs into a backtrace shown in the browser after the error message:

```
Machinery::Errors::SystemDescriptionIncompatible at /ubuntu
ubuntu: format version 5, needs to be upgraded. Try './bin/machinery upgrade-format ubuntu' to upgrade it to the current version.

BACKTRACE

(expand)

JUMP TO: GET POST COOKIES ENV

    /data/chuller/machinery/lib/system_description.rb in rescue in from_hash
                  raise Machinery::Errors::SystemDescriptionIncompatible.new(name, json_format_version)
    /data/chuller/machinery/lib/system_description.rb in from_hash
              begin
    /data/chuller/machinery/lib/system_description.rb in load 
...
```

**Comment by mauromorales** [comment]
Can confirm. We are safe on the `list --html` side since the descriptions with an old version don't have a link.

For the cases when the user pastes the url we should probably show a page telling the user how to perform the upgrade.
