### ISSUE TITLE
"KeyError" with "compare --html" for descriptions w/ and w/o extracted files (extract_metadata branch)

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#1957]
Testing machinery from current "extract_metadata" branch - experimental features enabled.

If I compare two descriptions with and without extracted files, machinery will succeed for

```machinery compare sles-full-metadata-extract-only sles-full-metadata-extract-notonly```

but fails with "KeyError" (key not found: "extracted") for

```machinery compare --html sles-full-metadata-extract-only sles-full-metadata-extract-notonly```

Backtrace:
[KeyError_at_compare_sles-full-metadata-extract-only_sles-full-metadata-extract-notonly.html.gz](https://github.com/SUSE/machinery/files/121555/KeyError_at_compare_sles-full-metadata-extract-only_sles-full-metadata-extract-notonly.html.gz)

**Comment by mauromorales** [comment]
can confirm, just stumbled into this issue. I'll have a look at it

**Comment by mauromorales** [comment]
fixed
