### ISSUE TITLE
Machinery allows you to compare old descriptions but then you can't diff files

### ISSUE THREAD

**Issue by mauromorales** [SUSE/machinery#1998]
If I run the comparison with machinery version 1.18 and two descriptions that are on schema version 5 machinery won't complain but once checking the html output the diff functionality for unmanaged files doesn't work

![cant open diffs](https://cloud.githubusercontent.com/assets/433958/13456507/c698ef58-e063-11e5-890b-2bd5fe7a80a3.png)

**Comment by thardeck** [comment]
The issue appeared when an upgrade happened when the page was opened. It does not happen on reload.
