### ISSUE TITLE
the experimental feature page is not listing the containerize feature

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#2005]
https://github.com/SUSE/machinery/wiki/Experimental-Features contains a list of our experimental features, however the containerize command is not among them, although it is enabled when turning experimental features on

**Comment by fschueller** [comment]
Fixed in revision [ca41ec1](https://github.com/SUSE/machinery/wiki/Experimental-Features/ca41ec1d5ad068f4de6ca252396b48f31bbd8956)
