### ISSUE TITLE
HTML View doesn't List Name of a Broken System Description

### ISSUE THREAD

**Issue by svollath** [SUSE/machinery#2046]
While ```machinery list``` will warn you about a broken system description, e.g.:
```
test-props: This description is broken.
```
The warning differs for html view (for ```machinery serve``` and ```machinery list --html```):
```
Machinery::Errors::SystemDescriptionError
```
1. The description name is missing in html view (so, error for which description?)
2. The message in html view should be the same: "```<Name>```: This description is broken."

FYI: I broke this description by adding ```,"blafasel": true``` to the unmanaged_files section:
```
  "unmanaged_files": {
    "_attributes": {
      "extracted": false,
      "has_metadata": false,
      "blafasel": true
    },
```

**Comment by mauromorales** [comment]
The issue also happens when doing `machinery show` of the system with the broken description
