### ISSUE TITLE
Install on Centos 6.7 

### ISSUE THREAD

**Issue by terrorpup** [SUSE/machinery#2072]
Hi, I have tried to install machinery on a CentOS 6.7 box, I have updated the ruby to 1.9.3 but I am seeing the folloiwng errors when I try to run it. 

 machinery 
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/machinery.rb:94:in `require_relative': /usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/file_validator.rb:70: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG (SyntaxError)
    changes_proc = -> (file) { file["changes"] }
                       ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/file_validator.rb:70: syntax error, unexpected tLAMBEG, expecting keyword_end
    changes_proc = -> (file) { file["changes"] }
                              ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/file_validator.rb:70: syntax error, unexpected '}', expecting keyword_end
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/file_validator.rb:76: syntax error, unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG
      changes_proc = -> (file) { file["changes"]}
                         ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/file_validator.rb:76: syntax error, unexpected tLAMBEG, expecting keyword_end
      changes_proc = -> (file) { file["changes"]}
                                ^
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/file_validator.rb:76: syntax error, unexpected '}', expecting keyword_end
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/lib/machinery.rb:94:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/bin/machinery:20:in `require_relative'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/machinery-tool-1.20.0/bin/machinery:20:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/machinery:22:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/machinery:22:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

**Comment by thardeck** [comment]
Thx for the report.

The mentioned issue is not hard to fix but the problem is that at least one of our gems requires Ruby 2.0 so I it makes more sense for us to increase the requirement.

Especially since Ruby 1.9 is not supported anymore upstream.

**Comment by mauromorales** [comment]
@terrorpup could you try it out on ruby 2.0.0 or greater?

**Comment by terrorpup** [comment]
No, I will try later today and let you know. Thanks for the input.

**Comment by terrorpup** [comment]
I know you guys close the ticket, but I want to let you know I have update my Ruby 2.3.1 and it working great now. Again, thanks for the help.

**Comment by mauromorales** [comment]
@terrorpup thanks a lot for the update :) and for opening the issues .. happy to help you!
