### ISSUE TITLE
Machinery with CentOS reported a bug

### ISSUE THREAD

**Issue by terrorpup** [SUSE/machinery#2074]
I was doing a for loop trying to pull in a group of systems, when it was trying to run the group it gave the following error

Inspecting groups...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/plugins/groups/groups_inspector.rb:52:in `block in parse_groups': undefined method `split' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/plugins/groups/groups_inspector.rb:41:in `map'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/plugins/groups/groups_inspector.rb:41:in `parse_groups'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/plugins/groups/groups_inspector.rb:29:in `inspect'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/lib/inspect_task.rb:87:in `block in build_description'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/lib/inspect_task.rb:79:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/lib/inspect_task.rb:79:in `build_description'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/lib/inspect_task.rb:21:in `inspect_system'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/lib/cli.rb:617:in `block (2 levels) in <class:Cli>'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/gli-2.13.4/lib/gli/command_support.rb:126:in `execute'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/gli-2.13.4/lib/gli/app_support.rb:296:in `block in call_command'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/gli-2.13.4/lib/gli/app_support.rb:309:in `call_command'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/gli-2.13.4/lib/gli/app_support.rb:83:in `run'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/machinery-tool-1.20.0/bin/machinery:41:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/machinery:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/machinery:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by thardeck** [comment]
Thx for the report. Can you provide your /etc/group file if there is nothing sensitive in it?

**Comment by thardeck** [comment]
In the latest release 1.22.1, the case is handled, by showing an error message how to fix the issue.

**Comment by thardeck** [comment]
@terrorpup 
Can you retry with the latest 1.22.1 release? It does have some fixes for the CentOS specific sudoers.conf configuration which might also handle your issue.

**Comment by thardeck** [comment]
I think machinery was unable to read the files because of the sudo issue on CentOS which is handled in the latest release.
If the issue still happens for your with version 1.22.1, please reopen this bug.

**Comment by terrorpup** [comment]
Sorry just saw this will try later today
