### ISSUE TITLE
Machinery does not recognize CentOS 7.2

### ISSUE THREAD

**Issue by tomazb** [SUSE/machinery#2077]
Hello!

When inspecting CentOS 7.1 and 7.2 I get this:

Inspecting os...
 -> Inspection failed!

In the logs I can see attempt to read /etc/redhat-release.

Is this known thing?

**Comment by tomazb** [comment]
Weird... In some cases it gets it:
Inspecting os...
 -> Found operating system 'CentOS Linux 7 (Core)' version '7 (Core)'.

# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core)

**Comment by cornelius** [comment]
What are the permissions of the file `etc/redhat-release`?

**Comment by TheBigBear** [comment]
I think I am running into the same (or very similar) issue on Centos 6.8 and Centos 7.2 see
https://github.com/SUSE/machinery/issues/2136 and https://github.com/SUSE/machinery/issues/2137

@cornelius the ```/etc/redhat-release``` permissions are:

```ls -l /etc/redhat-release``` 
```
lrwxrwxrwx. 1 root root 14 May 27 10:52 /etc/redhat-release -> centos-release
```

```ls -l /etc/centos-release```
```
-rw-r--r--. 1 root root 38 Dec  9  2015 /etc/centos-release
```

**Comment by thardeck** [comment]
Hi @tomazb  , thx for reporting the issue.

The reason for it is that sudo on CentOS by default requires a Terminal session.

As a workaround you can comment out the line
```
# Defaults    requiretty
```
in your /etc/sudoers by running `visudo`.

We are considering the `-t` option for ssh but it is not decided yet.

**Comment by thardeck** [comment]
In the latest release 1.22.1, the case is handled, by showing an error message how to fix the issue.
