### ISSUE TITLE
Comparison view displays single results inconsistently

### ISSUE THREAD

**Issue by fschueller** [SUSE/machinery#2094]
When viewing the comparison of two descriptions in the HTML view, the results get shown underneath their respective description title. However, if there's only a single result (e.g. there are only patterns existing in one of the descriptions), all content gets shifted to the left. This breaks the consistency of the view for the description shown on the right.

![snapshot3](https://cloud.githubusercontent.com/assets/11717425/15323258/765be904-1c41-11e6-88ac-166d70b68cad.png)

**Comment by mauromorales** [comment]
@fschueller if you still have the systems could you upload a screenshot?
