### ISSUE TITLE
rsync is not installed on minimal systems

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#2118]
A user reported an issue that `rsync` is not always installed on openSUSE systems and thus Machinery fails when extracting files. For example, on minimal installation systems.

**Comment by MalloZup** [comment]
@mschnitzer  thx. my suggestion is just to add rsync to spec files of machinery , to avoid this situation

**Comment by mschnitzer** [comment]
I think, this is not really needed. Not everyone needs this functionality. I'd rather suggest to print a note to the user to install `rsync` instead.
