### ISSUE TITLE
machinery export description to html format

### ISSUE THREAD

**Issue by MalloZup** [SUSE/machinery#2119]
### How To Reproduce:

I'm using machinery for automation in a QA-automation environment, machinery works well together in a Jenkins server, plus other stuff. 

I really like the inspect functionality of machinery, and for QA-automation is a good feature.

The  only one issue i found, is that, after i get the description json, i cannot really have an html file of the description.

So : 

```
machinery inspect IP_ADRESS_OF_SUT(Systems under Tests)
```
I have the description. This is stored in json format.

I would like to have a feature like this:

```
machinery convert-html IP_ADRESS_OF_SUT  
```
With this feature i could then copy the .html file and put it in the workspace dir of Jenkins, or to a web-server.

In my env. i cannot use machinery serve  or show --html because: 
*1) i don't want to expose the jenkins server ip
*2) this would be not nice for  the testing workflow. 
3) i don't want to create a web-server

**Comment by mschnitzer** [comment]
A temporary workaround might be: Start a web server, download with curl the HTML view.

(If you want a quick solution)

**Comment by MalloZup** [comment]
@mschnitzer  thx. i can make a short hack for that :) helps a quick solution :)

**Comment by thardeck** [comment]
This feature was added to master and a new version will be released soon.

**Comment by thardeck** [comment]
@MalloZup The version for openSUSE was released and SLES is in the maintenance queue.
