### ISSUE TITLE
ssh connection reset by peer

### ISSUE THREAD

**Issue by joelgordon** [SUSE/machinery#2128]
I have been having errors when trying to use machinery on both Azure, and GCE instances. All of the servers are running sles 11 sp3. I am running the commands from opensuse (42.1). In each case they connect to the server and start gathering information. Then the process exits with the error  "ssh_exchange_identification: read: Connection reset by peer". This happens while either gathering user or group information.  Please let me know if I can provide any more information.

**Comment by mschnitzer** [comment]
Please double check the logs of the remote SSH server you connect to. It seems like an issue with the remote server.

**Comment by joelgordon** [comment]
Issue only seems to happen when I'm in the office. I will work with our network engineers. Sorry for the noise.
