### ISSUE TITLE
cannot find PREREQUISITES

### ISSUE THREAD

**Issue by jubalh** [SUSE/machinery#2134]
machinery tells me to look at PREREQUISITES section in the manual. I dont see that in neither 'machinery man --html' nor in http://machinery-project.org/docs/

**Comment by mauromorales** [comment]
@jubalh I think you need to go to the docs of the specific command you are running and then you will find a section there. For example: http://machinery-project.org/machinery-inspect.1/ around the middle of the page. Same thing for every other command

**Comment by jubalh** [comment]
Got it. Thanks.
