### ISSUE TITLE
wrong dpkg-query call when executing "machinery inspect localhost" on Ubuntu 16.04

### ISSUE THREAD

**Issue by Supersonic112** [SUSE/machinery#2138]
Hello there,

I recently installed Machinery 1.21 (along with all requirements) on Ubuntu 16.04 running in a KVM virtual machine.

When running 'machinery inspect localhost' as root, the program works for a while and then crashes at the step 'Inspecting changed-config-files' with an error that seems to indicate machinery tried to get information on a package named 'diversion by branding-ubuntu from' using dpkg-query, so the problem seems to be that this line sneaked into the list of package names somehow and the crash occurs because dpkg-query does not accept package names that contain a space. The log of the crash including backtrace is appended below.

Greetings and thanks in advance
Supersonic

[machinery-dpkg-error.txt](https://github.com/SUSE/machinery/files/455002/machinery-dpkg-error.txt)

**EDIT:**
_.machinery/machinery.log_ reveals that the last successful command was `dpkg -S /usr/share/gnome-mahjongg/themes/postmodern.svg` which returns these three lines:
`diversion by branding-ubuntu from /usr/share/gnome-mahjongg/themes/postmodern.svg`
`diversion by branding-ubuntu to: /usr/share/gnome-mahjongg/themes/postmodern.svg.unbranded`
`gnome-mahjongg, branding-ubuntu: /usr/share/gnome-mahjongg/themes/postmodern.svg`

**Comment by thardeck** [comment]
Hi @Supersonic112, thx for reporting the issue. I can reproduce the issue on my test system and will look into fixing it soon.
