### ISSUE TITLE
How to change rsync option?

### ISSUE THREAD

**Issue by nerocide** [SUSE/machinery#2242]
Hi,

during an full inspection, retreiving files from a destination host can take some time.
It would be nice to use rsync's **-z** (compress) option.

I'm wondering if there is a way to change rsync behaviour in machinery. So far **machinery config** display very few options.

I wasn't able to find anything in the documentation as well.
Please let me know if you have any hints.

Regards.

**Comment by thardeck** [comment]
Hi @nerocide,

we do not use `rsync -z` but we only use rsync for transferring `changed managed` und `changed config` files which are usually not that many and they are not that huge by average.

The big chunk comes from unmanaged-files which are compressed with gzip before transferring them through ssh so no additional compression is required.


There is no machinery option for the `-z` option but I think you could configure your ssh connections to use compression like this: https://askubuntu.com/questions/6770/does-ssh-use-any-compression

Although in my experience the ssh compression slows the connection usually more down, then gained by the compression unless your are transferring huge text files.
