### ISSUE TITLE
Machinery should not interpret a hostname

### ISSUE THREAD

**Issue by gaitjan** [SUSE/machinery#2260]
I try to reach a host using `LocalForward`. This is what happened:

```
gait@alpaca:~/.machinery> machinery inspect --ssh-port 2222 --name ut3s localhost

Inspecting localhost for os, packages, patterns, repositories, users, groups, services, changed-config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Need to be root to inspect local system.
gait@alpaca:~/.machinery>
```

Solved this by having this in `/etc/hosts`:
`127.0.0.1       localhost       lokaal`
so I could do
`machinery inspect --ssh-port 2222 --name ut3s lokaal`

**Comment by thardeck** [comment]
Yes, `localhost` is used to trigger the non-ssh inspection with root.

If you want to use ssh for local inspection you can use the local ip `127.0.0` which should also work for local redirects.

I think it should be ok this way.
