### ISSUE TITLE
machinery inspect failed on SLES 12 SP3

### ISSUE THREAD

**Issue by hashio** [SUSE/machinery#2261]
$ machinery inspect IP
Inspecting IP for os, packages, patterns, repositories, users, groups, services, changed-config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'SUSE Linux Enterprise Server 12 SP3' version '12-SP3'.
Inspecting packages...
 -> Found 1949 packages.
Inspecting patterns...
 -> Found 14 patterns.
Inspecting repositories...
 -> Found 40 repositories.
Inspecting users...
 -> Found 38 users.
Inspecting groups...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Traceback (most recent call last):
        15: from /usr/bin/machinery:23:in `<main>'
        14: from /usr/bin/machinery:23:in `load'
        13: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/bin/machinery:41:in `<top (required)>'
        12: from /usr/lib64/ruby/gems/2.5.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
        11: from /usr/lib64/ruby/gems/2.5.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
        10: from /usr/lib64/ruby/gems/2.5.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
         9: from /usr/lib64/ruby/gems/2.5.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
         8: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/lib/cli.rb:768:in `block (2 levels) in <class:Cli>'
         7: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:21:in `inspect_system'
         6: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:79:in `build_description'
         5: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:79:in `each'
         4: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/lib/inspect_task.rb:87:in `block in build_description'
         3: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:30:in `inspect'
         2: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:42:in `parse_groups'
         1: from /usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:42:in `map'
/usr/lib64/ruby/gems/2.5.0/gems/machinery-tool-1.23.1/plugins/groups/groups_inspector.rb:53:in `block in parse_groups': undefined method `split' for nil:NilClass (NoMethodError)

**Comment by thardeck** [comment]
@hashio Thanks for the report and sorry for the late reply. Could you provide the file `/etc/group` from the inspected system?
There should be no private content in this file but please make sure before posting that this is the case.

It seems Machinery has an issue parsing `/etc/group`.

**Comment by hashio** [comment]
@thardeck 
I am checked again for /etc/group.
Sorry It's my mistake. my manual edit was failed.
a last colon missing group line is found in /etc/group

wrong: influxdb:x:1004
fixed:   influxdb:x:1004:

rerun machinary  inspect was succeeded

**Comment by thardeck** [comment]
@hashio No problem, thanks for the update. Closing this issue then.
