### ISSUE TITLE
Fedora 30 needs rake installed in order to build latest machinery

### ISSUE THREAD

**Issue by tomazb** [SUSE/machinery#2278]
I followed the instruction for other systems as I wanted to install machinery on Fedora 30. It failed because of missing rake. So the line should be

dnf install ruby rubygems rake ruby-devel gcc zlib-devel patch xdg-utils make golang

You can see that building native gem fails without the rake and works with rake installed:

bash-5.0$ sudo gem install machinery-tool
Fetching abstract_method-1.2.1.gem
Successfully installed abstract_method-1.2.1
Fetching cheetah-0.5.1.gem
Successfully installed cheetah-0.5.1
Fetching builder-3.2.3.gem
Successfully installed builder-3.2.3
Fetching gli-2.19.0.gem
Successfully installed gli-2.19.0
Fetching public_suffix-4.0.1.gem
Successfully installed public_suffix-4.0.1
Fetching addressable-2.7.0.gem
Successfully installed addressable-2.7.0
Fetching json-schema-2.8.1.gem
Successfully installed json-schema-2.8.1
Fetching temple-0.8.2.gem
Successfully installed temple-0.8.2
Fetching tilt-2.0.10.gem
Successfully installed tilt-2.0.10
Fetching haml-5.1.2.gem
Successfully installed haml-5.1.2
Fetching kramdown-2.1.0.gem
Successfully installed kramdown-2.1.0
Fetching rack-2.0.7.gem
Successfully installed rack-2.0.7
Fetching rack-protection-2.0.7.gem
Successfully installed rack-protection-2.0.7
Fetching mustermann-1.0.3.gem
Successfully installed mustermann-1.0.3
Fetching sinatra-2.0.7.gem
Successfully installed sinatra-2.0.7
Fetching mimemagic-0.3.3.gem
Successfully installed mimemagic-0.3.3
Fetching diffy-3.3.0.gem
Successfully installed diffy-3.3.0
Fetching machinery-tool-1.24.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing machinery-tool:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/machinery-tool-1.24.1/machinery-helper
rake RUBYARCHDIR\=/usr/local/lib64/gems/ruby/machinery-tool-1.24.1 RUBYLIBDIR\=/usr/local/lib64/gems/ruby/machinery-tool-1.24.1
rake failedNo such file or directory - rake

Gem files will remain installed in /usr/local/share/gems/gems/machinery-tool-1.24.1 for inspection.
Results logged to /usr/local/lib64/gems/ruby/machinery-tool-1.24.1/gem_make.out
bash-5.0$ sudo dnf install rake
Last metadata expiration check: 0:07:34 ago on pet 29 nov 2019 14:00:02 CET.
Dependencies resolved.
=======================================================================================================
 Package                   Architecture        Version                      Repository            Size
=======================================================================================================
Installing:
 rubygem-rake              noarch              12.3.2-124.fc30              updates               96 k

Transaction Summary
=======================================================================================================
Install  1 Package

Total download size: 96 k
Installed size: 267 k
Is this ok [y/N]: y
Downloading Packages:
rubygem-rake-12.3.2-124.fc30.noarch.rpm                                176 kB/s |  96 kB     00:00    
-------------------------------------------------------------------------------------------------------
Total                                                                   74 kB/s |  96 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                               1/1 
  Installing       : rubygem-rake-12.3.2-124.fc30.noarch                                           1/1 
  Running scriptlet: rubygem-rake-12.3.2-124.fc30.noarch                                           1/1 
  Verifying        : rubygem-rake-12.3.2-124.fc30.noarch                                           1/1 

Installed:
  rubygem-rake-12.3.2-124.fc30.noarch                                                                  

Complete!
bash-5.0$ sudo gem install machinery-tool
Building native extensions. This could take a while...
Successfully installed machinery-tool-1.24.1
Parsing documentation for machinery-tool-1.24.1
Installing ri documentation for machinery-tool-1.24.1
Done installing documentation for machinery-tool after 1 seconds
1 gem installed

**Comment by thardeck** [comment]
Thanks for your report.

I have updated the wiki page accordingly: https://github.com/SUSE/machinery/wiki/Installation-on-Other-Distributions/_compare/76c02f1271c1b150f3bbbc36b7df0d7828fc2d71...befa04c9bbe07fd438e3abc800307ca1c031d381
