### ISSUE TITLE
Switch off Prophet comments

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#312]
Prophet comments on each pull request at least once and additionally when master changes. This creates quite some noise in terms of repeated comments and email notification. For me it would be enough to set the state of the tests via the status API (and possibly add a "Details" link there, but that's not mandatory). So I would suggest to switch off commenting in Prophet (it still should continue to run and set the status according to test results, of course).

**Comment by aduffeck** [comment]
This has been implemented meanwhile.
