### ISSUE TITLE
Use more discoverable and standard locations to store Machinery data

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#328]
We currently store all Machinery data in `~/.machinery`. This includes the system descriptions, the log file, and the configuration file. This approach has two issues, on one hand it doesn't follow the XDG Base Directory standard for configuration files, and on the other hand it gives the impression that the system descriptions are not to be accessed by the user, because they are in a hidden directory.

Following up on a discussion in #268 I would like to propose the following solution:

* Use the XDG standard to store the configuration file. By default it would end up in `~/.config/machinery.conf`.
* Ask the user when running Machinery where to store the system descriptions and provide a default of `~/machinery-descriptions`. This would give users the option to choose according to their preferences, and make it clear and explicit for users, where the data will be stored.
* Store the log file in the descriptions directory. The log file is associated with the descriptions, so this is a natural place for it.

**Comment by promulo** [comment]
hi @cornelius, are you guys still interested on this? I was thinking about taking it but it's a quite old issue :)

**Comment by cornelius** [comment]
Seems like people are actually happy with the current location.
