### ISSUE TITLE
Man page not accessible when installing from gem

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#348]
The gem installs the man page as part of its gem-specific files, but not at a location accessible by the `man` command by default. While this seems to be the standard practice for gems, it would be great, if there would be an easy way to access the man page.

I would suggest to implement a command `machinery man`, which shows the man page just as `man machinery` would, if the man page would be installed properly.

**Comment by thardeck** [comment]
I am not sure if we should address this since most gems seem to completely ignore man pages.

**Comment by cornelius** [comment]
I don't think it is a valid argument that other gems ignore man pages. Users need to have to access to the documentation no matter how they install.
