### ISSUE TITLE
`machinery generate-html` doesn't show export location

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#499]
If a user runs `machinery generate-html <name>` there is no information were the html file is exported. It is mentioned in the man page but not during command usage.

A hint might be helpful.

**Comment by thardeck** [comment]
We should also export it elsewhere since the assets directory looks like a scope directory and it is not that easy for the user to export the html export somewhere.

I would prefer a tmp directory where the user can just copy the whole directory to the destination target.

**Comment by cornelius** [comment]
As a first step we will implement the hint.

**Comment by vwallfahrer** [comment]
Fixed #766

**Comment by mauromorales** [comment]
I added the hint to give the specification about the html file and assets folder. But I agree with @thardeck on having these two inside a directory of it's on (i.e. html)

could we change the specification of #866 to be that? otherwise we can do it later depending on it's priority.

cc. @keberle94
