### ISSUE TITLE
Validation errors break display of `machinery list`

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#510]
When a description has a validation error it is shown in the output of `machinery list`, but it's not indented properly and it's shown at the wrong location. Example:

```
Warning: File validation errors:
Error validating description 'config-files-bad'

Scope 'config_files':
  * File '/home/cs/.machinery/config-files-bad/config_files/etc/postfix/main.cf' doesn't exist
 config-files-bad:
   * config-files (extracted)
```

**Comment by keberle94** [comment]
This issue is not relevant any more, because in the past the validation was disabled for the machinery list command.
