### ISSUE TITLE
machinery copy and machinery list ignore commandline arguments

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#554]
`machinery copy host1 host2 superfluous` and `machinery list superfluous` silently ignore the `superfluous` argument.

**Comment by tgoettlicher** [comment]
See: https://github.com/SUSE/machinery/issues/554

**Comment by mauromorales** [comment]
Closing this since we are not going to ignore in these cases but supply an error saying that the command expects less arguments and showing the help message.
