### ISSUE TITLE
export-autoyast on a RHEL box it's not showing that the operation is not supported

### ISSUE THREAD

**Issue by gsanso** [SUSE/machinery#556]
`machinery export-autoyast` should show an error that this operation is not supported for RHEL

When running  `machinery export-autoyast` on a RHEL box it's not showing that the operation is not supported 

```
 machinery export-autoyast -a /tmp/qlo rhbox

```

Unmanaged files following these patterns are not exported:
var/lib/rpm/*
etc/passwd*
etc/shadow*
etc/group*
etc/fstab
lib/mkinitrd
etc/udev/rules.d/70-persistent-net.rules
var/log/*
etc/default/grub*

Note: The permssions of the AutoYaST directory are restricted to be only accessible by the current user. Further instructions are provided by the README.md in the exported directory.
Exported to '/tmp/qlo/rhbox-autoyast'.

**Comment by gsanso** [comment]
"os": {
    "name": "Red Hat Enterprise Linux Server",
    "version": "6.6 (Santiago)",
    "architecture": "x86_64"
  },

**Comment by gsanso** [comment]
For the tests I manually added these repositories to the system description:


 "repositories": [
    {
      "alias": "SLES12-12-0",
      "name": "SLES12-12-0",
      "type": "yast2",
      "url": "cd:///?devices=/dev/disk/by-id/ata-QEMU_DVD-ROM_QM00001",
      "enabled": true,
      "autorefresh": false,
      "gpgcheck": true,
      "priority": 99
    },
    {
      "alias": "SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Debuginfo-Pool",
      "name": "SLES12-Debuginfo-Pool",
      "type": null,
      "url": "https://updates.suse.com/SUSE/Products/SLE-SERVER/12/x86_64/product_debug?5bc3650926e7f0c7ef4858047c5f135111a869a2caecbafecdbe4e9b9af8fcb24df95e44310b33fc4ff43d2a5a835a2122c34db891f104edd849e298e79da83d29bff25f12472e70eca97471f03365a20055a67c5778d898c4c6c35179ce959c57",
      "enabled": false,
      "autorefresh": false,
      "gpgcheck": true,
      "priority": 99
    },
    {
      "alias": "SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Debuginfo-Updates",
      "name": "SLES12-Debuginfo-Updates",
      "type": null,
      "url": "https://updates.suse.com/SUSE/Updates/SLE-SERVER/12/x86_64/update_debug?5bc3650926e7f0c7ef4858047e5f135146d93a2750ff1bf2a50bce3f49c954b04b11d74b382faa164a635d7d1b70d37a9141e759bd8c907df7fba2c8653e0c8e14b8dbadb13c8cc96e0f44b7ed97eed32b52d83a67e89103190923b7205598",
      "enabled": false,
      "autorefresh": true,
      "gpgcheck": true,
      "priority": 99
    },
    {
      "alias": "SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool",
      "name": "SLES12-Pool",
      "type": "rpm-md",
      "url": "https://updates.suse.com/SUSE/Products/SLE-SERVER/12/x86_64/product?5bc3650926e7f0c7ef4858047a5f1351f4239abe4dc5aafc7061cc2b47c1c54d21e53b8150115ffdd717636c1a2686268e4ae463bbb1f318fea4234fa7202173edaf719b08671ff733d5a5695b1bd052deae102819327f8ac6ec4d",
      "enabled": true,
      "autorefresh": false,
      "gpgcheck": true,
      "priority": 99
    },
    {
      "alias": "SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Updates",
      "name": "SLES12-Updates",
      "type": "rpm-md",
      "url": "https://updates.suse.com/SUSE/Updates/SLE-SERVER/12/x86_64/update?5bc3650926e7f0c7ef485805725f135153d25d5137743176f0365397681adec894b25c0c6d9784d8d5c81258b2be6b675d80082e4457d838b355b45994851352e3767717c245c806d7fa1f071272021f90f6a865728b337161",
      "enabled": true,
      "autorefresh": true,
      "gpgcheck": true,
      "priority": 99
    }
  ],

**Comment by gsanso** [comment]
Full system description generated during tests here:  http://pastebin.suse.de/12404

**Comment by cornelius** [comment]
I can't reproduce this problem. Are you on the lastest master?

**Comment by cornelius** [comment]
@gsanso Could you please test again with the latest packages. This works for me.

**Comment by gsanso** [comment]
@cornelius Sorry I used wrong version. Please close/delete this issue.
