### ISSUE TITLE
Hint shown by 'machinery upgrade-format' leads to endless loop

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#579]
When 'machinery upgrade-format' fails it advises to run the same command again. This hint is misleading and confuses the user.

```
# machinery upgrade-format broken
Upgrading description "broken" failed:
The system description 'broken' has an incompatible data format and can not be read.
Try 'machinery upgrade-format broken' to upgrade it to the current version.
```

**Comment by Werni** [comment]
I debugged it and it is a basic machinery problem. We try to load a scope which does not exist as result we try to access a nil variable.  

See lib/system_description.rb line 112.

**Comment by cornelius** [comment]
Things to do to fix this bug:

* [ ] Change file validation code to not depend on data model
* [ ] Implement file validation code for old schema
* [ ] Fix misleading error message
