### ISSUE TITLE
Misleading message about file extraction

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#614]
`machinery inspect` prints a misleading message about file extraction.
It says 'Extracted 311 unmanaged files and trees.' although these files were not extracted because rsync is missing.

```
Inspecting unmanaged-files...
The content of the following special directories is ignored: /proc, /sys, /dev, /dev/shm, /run, /sys/fs/cgroup.
 -> Extracted 311 unmanaged files and trees.
Inspecting repositories...
 -> Found 0 repositories

Errors while inspecting changed-managed-files:
 -> Need binary 'rsync' to be available on the inspected system.

Errors while inspecting config-files:
 -> Need binary 'rsync' to be available on the inspected system.
```

**Comment by ajaeger** [comment]
Unmanaged files was really successful, error manages is for scope changed-managed-files.

**Comment by thardeck** [comment]
Related to #633. If we fix 633 by using tarballs then rsync wouldn't be needed anymore.
