### ISSUE TITLE
Identical scopes are not shown in compare unless all are identical

### ISSUE THREAD

**Issue by thardeck** [SUSE/machinery#631]
If I create a copy of a system description which has all scopes inspected and remove the os scope before comparison, I get the following output:

```
# Operating system
  Unable to compare, no data in 'one_scope_removed'
```

This is quite confusing since there is no output about everything else being identical.

The identical message is only shown if everything is identical.

**Comment by keberle94** [comment]
The missing information was added by commit: 590d57e60d91fc2dab31a8ee13c5fb4558468951 . So we close this bug as fixed.
