### ISSUE TITLE
autoyast fails when hostip is specified

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#644]
The exported autoyast installation fails when the hostip incl. netmask is specified behind the autoyast parameter:
``autoyast=http://192.168.1.1/install/autoyast/autoinst.xml hostip=192.168.1.2/24``

This makes the sed expression fail: 
 https://github.com/SUSE/machinery/blob/master/lib/autoyast.rb#L253

The result is corrupted config files on the installed system.

**Comment by thardeck** [comment]
Fixed
