### ISSUE TITLE
`machinery inspect -s repositories` fails on RHEL5

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#660]
The helper script fails on RHEL5 because of following reasons:

* The helper script uses the module `json` which was introduced in python 2.6:
  https://github.com/SUSE/machinery/blob/master/helpers/yum_repositories.py#L20

* The `if` construct as it is used in the helper script was introdcued in python 2.5:
  https://github.com/SUSE/machinery/blob/master/helpers/yum_repositories.py#L31

* RHEL5 ships python 2.4.

**Comment by thardeck** [comment]
Fixed by #666
