### ISSUE TITLE
--skip-files does not handle ../ in directory name

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#695]
Following line does not skip the /opt directory:

```
# machinery inspect hostname -x  --scope unmanaged-files --skip-files=/etc/../opt
```

This is a minor bug. However, specifying files like this is valid in UNIX/Linux. This might occure for example when scripts call machinery.

**Comment by cornelius** [comment]
Works as expected. Matcher does only literal matching.

We should document this, though.
