### ISSUE TITLE
no warning for scope os that --skip-files is not supported

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#699]
The card for the feature states:

'Add warning for files scopes where the `--skip-files` switch isn't supported yet'

however:

-------------------skip---------------------
./bin/machinery inspect --skip-files "/tmp" -s os 192.168.121.244
Inspecting 192.168.121.244 for os...
Warning: System Description validation errors:
In scope unmanaged_files: The property (files) of type Array matched more than one of the required schemas.
Inspecting os...
 -> Found operating system 'SUSE Linux Enterprise Server 12' version '12'.

Hint: To show the data of the system you just inspected run:
./bin/machinery show 192.168.121.244

Hint: To do a full inspection containing all scopes and to extract files run:
./bin/machinery inspect 192.168.121.244 --name 192.168.121.244 --extract-files
-------------------skip---------------------

The expected warninng seems to be missing.

**Comment by aduffeck** [comment]
The warning should only be shown for files scopes, so it is correct that it doesn't show up for the `os` scope. There was still a problem with the code, though, which is fixed by my pull request.
