### ISSUE TITLE
Add support for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by boblmartens** [SUSE/machinery#802]
I'm wondering if it would be possible to add support for openSUSE Tumbleweed along with openSUSE 13.2/13.1.

Thanks!

**Comment by thardeck** [comment]
Hey, do you mean support for inspection or running machinery on it since packages are already built for Tumbleweed: https://build.opensuse.org/project/show/systemsmanagement:machinery

**Comment by boblmartens** [comment]
Inspection as well. When I run the bare machinery command it says that the platform is not supported. 

Sincerely,
Bob Martens

http://bobmartens.net
@boblmartens

**Comment by thardeck** [comment]
Yes, you are right. Tumbleweed support will be shipped with one of the next versions.

**Comment by boblmartens** [comment]
Thank you!

Sincerely,
Bob Martens

http://bobmartens.net
@boblmartens
