### ISSUE TITLE
RHEL 5.x inspection: validation errors

### ISSUE THREAD

**Issue by gsanso** [SUSE/machinery#817]
Target OS: RHEL 5.10 x86_64

Machinery is showing validation errors after inspecting rhel: 

```
peon@dhcp95:~> machinery validate rhel510
Validation failed.
In scope unmanaged_files: The property #749 (files) of type Array did not match any of the required schemas.

```

**Comment by greygoo** [comment]
the problem originates from these entries:

------------------snip-----------------
      {
        "name": "/misc/",
        "type": "remote_dir"
      },
      {
        "name": "/net/",
        "type": "remote_dir"
      },
------------------snip-----------------

not sure while they were added I thought they ought to be filtered, will further investigate

**Comment by greygoo** [comment]
when inspecting I get 
---------------snip-----------------
The content of the following remote directories is ignored: /misc, /net.
---------------snip-----------------

**Comment by greygoo** [comment]
bug was introduced with commit 520f70b9dca5ea7493045d352b25d8719c326dfe
