### ISSUE TITLE
sudo error handling needs improvement

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#860]
When using a user different than root for inspections and no sudo rights are granted there are some issues:

--scope os -> error unkownOS is shown
--scope changed-configfiles -> 0 changed files are found in contrast  to 6 found when running inspection as root.

-> we need to make sure that if some command can not be executed while the inspection we need to clearly communicate this to the user and not silently continue and collect wrong data.

**Comment by tgoettlicher** [comment]
Fixed
