### ISSUE TITLE
kernel_require.rb:55:in `require': cannot load such file -- abstract_method (LoadError)

### ISSUE THREAD

**Issue by schwindp** [SUSE/machinery#927]
Note: I'm trying to run machinery on a FC21 box, haven't found any explicit warnings against it...
```
[pschwindt@korn:~/src/machinery]$ ruby bin/machinery 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- abstract_method (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/pschwindt/src/machinery/lib/machinery.rb:20:in `<top (required)>'
	from bin/machinery:20:in `require_relative'
	from bin/machinery:20:in `<main>'
```

machinery source was checked out right before, so it's up to date.

```
[pschwindt@korn:~/src/machinery]$ rpm -qa|grep ruby
rubygem-psych-2.0.5-29.fc21.x86_64
rubygem-json-1.8.1-29.fc21.x86_64
rubygem-io-console-0.4.3-29.fc21.x86_64
ruby-2.1.6-29.fc21.x86_64
rubypick-1.1.1-2.fc21.noarch
rubygems-2.2.2-101.fc21.noarch
rubygem-bigdecimal-1.2.4-29.fc21.x86_64
rubygem-rdoc-4.1.1-2.fc21.noarch
ruby-libs-2.1.6-29.fc21.x86_64
ruby-irb-2.1.6-29.fc21.noarch
```

**Comment by thardeck** [comment]
Thanks for your report. Fedora is atm not supported to run machinery although inspection of it should work.

How did you install machinery? The reason for your issue is the missing abstract_method gem.

But as soon as you have all required gems installed machinery would exit with a warning that the platform is not supported.

**Comment by schwindp** [comment]
Thanks for coming back that quickly: I pulled machinery from git this morning. 

And thanks for enlightening me regarding the missing gem, I'll have a look then.

(closing since unsupported on FC21, thanks for helping anyway)

**Comment by thardeck** [comment]
If you are using the git tree you can run `bundle install` in the machinery directory to install all required gems.

**Comment by thardeck** [comment]
So the error should now be a warning which also can be disabled by running `machinery config perform-support-check false`
