### ISSUE TITLE
Unit tests fail if run on a server not in a (UTC+1) timezone

### ISSUE THREAD

**Issue by oucsaw** [SUSE/machinery#961]
I'm trying to run the machinery unit tests on an openSUSE 13.2 (Harlequin) (x86_64) VM and they fail on `ListTask#list`:

```
  1) ListTask#list shows also the date and hostname of the descriptions if verbose is true
     Failure/Error: expect(captured_machinery_output).to include(expected_output)
       expected " foo:\n   * packages\n      Host: [example.com]\n      Date: (2014-02-07 14:04:45)\n   * repositories\n      Host: [example.com]\n      Date: (2014-02-07 14:04:45)\n\n" to include " foo:\n   * packages\n      Host: [example.com]\n      Date: (2014-02-07 15:04:45)\n"
       Diff:
       @@ -1,2 +1,8 @@
       - foo:\n   * packages\n      Host: [example.com]\n      Date: (2014-02-07 15:04:45)\n
       + foo:
       +   * packages
       +      Host: [example.com]
       +      Date: (2014-02-07 14:04:45)
       +   * repositories
       +      Host: [example.com]
       +      Date: (2014-02-07 14:04:45)
```
The error seems to be down to the fact the expected date is `2014-02-07 15:04:45` and the date returned is `2014-02-07 14:04:45` (which is what I would expect in the timezone I am in). 

You can make this more obvious by choosing a more exotic timezone (e.g `TZ='Antarctica/Rothera'; export TZ`).

There are various fixes to this but the simplest seems to be:
```
@@ -23,9 +23,8 @@ describe ListTask do
   let(:list_task) { ListTask.new }
   let(:store) { SystemDescriptionStore.new }
   let(:name) { "foo" }
-  let(:date) { "2014-02-07T14:04:45Z" }
+  let(:date) { "2014-02-07 14:04:45" }
   let(:hostname) { "example.com" }
-  let(:date_human) { "2014-02-07 15:04:45" }
   let(:system_description) {
     create_test_description(
       scopes: ["packages", "repositories"], modified: date, hostname: hostname,
@@ -90,7 +89,7 @@ EOF
  foo:
    * packages
       Host: [#{hostname}]
-      Date: (#{date_human})
+      Date: (#{date})
 EOF
       list_task.list(store, verbose: true)
```

However, I'm assuming that there may have been a reason to define `:date` and `:date_human` in the first place, which this would undo.

Are there any objections to the above as a fix ? (Or should I just move to a better timezone ;-) )

**Comment by mauromorales** [comment]
I did a test on this and can confirm the issue.

@oucsaw haha please don't change timezone, might take too long to close the issue :P

**Comment by mauromorales** [comment]
@oucsaw the latests update to master should fix the problem. I'm closing the issue for now as tests seem to pass on different time zones but please update and double check that it's working for you. Thanks a lot for submitting the issue :)

**Comment by oucsaw** [comment]
Thanks! the unit tests now pass
