### ISSUE TITLE
RHEL 4.7 Inspection error

### ISSUE THREAD

**Issue by alexrenna** [SUSE/machinery#973]
error output:
machinery-test:~ # machinery inspect rhel4
Inspecting rhel4 for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)

Inspecting os...
 -> Found operating system 'Red Hat Enterprise Linux AS' version '4 (Nahant Update 7)'.
Inspecting packages...
 -> Found 808 packages.
Inspecting patterns...
 -> Patterns are not supported on this system.
Inspecting repositories...
 -> Inspection failed!
Inspecting users...
 -> Found 35 users.
Inspecting groups...
 -> Found 44 groups.
Inspecting services...
 -> Found 78 services.
Inspecting config-files...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
Execution of "ssh root@rhel4 LC_ALL\=C stat --printf \\\%a:\\\%U:\\\%G:\\\%u:\\\%g:\\\%n\\\\n /etc/openldap/ldap.conf /etc/pam_smb.conf /etc/pam.d/system-auth /etc/samba/smb.conf /etc/selinux/targeted/booleans /etc/ldap.conf /etc/sysconfig/system-config-securitylevel /etc/login.defs /etc/inittab /etc/krb.conf /etc/xml/catalog /usr/share/sgml/docbook/xmlcatalog /etc/hotplug/usb.usermap /etc/cups/cupsd.conf" failed with status 1: stat: unrecognized option `--printf' (...).

Error output:
stat: unrecognized option `--printf'
Try `stat --help' for more information.

Backtrace:
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:555:in `check_errors'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/cheetah-0.4.0/lib/cheetah.rb:364:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/logged_cheetah.rb:24:in `block in run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/helper.rb:55:in `with_env'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/helper.rb:45:in `with_c_locale'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/logged_cheetah.rb:23:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/remote_system.rb:77:in `run_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/changed_rpm_files_helper.rb:90:in `get_file_properties'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/changed_rpm_files_helper.rb:120:in `get_path_data'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/plugins/config_files/config_files_inspector.rb:101:in `inspect'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/inspect_task.rb:86:in `block in build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/inspect_task.rb:78:in `each'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/inspect_task.rb:78:in `build_description'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/inspect_task.rb:23:in `inspect_system'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/lib/cli.rb:513:in `block (2 levels) in <class:Cli>'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.8.2/bin/machinery:28:in `<top (required)>'
/usr/bin/machinery:26:in `load'
/usr/bin/machinery:26:in `<main>'

how to reproduce:
clean install of a RHEL 4.7, Machinery version is Version  : 1.8.2 Release : 25.1

**Comment by thardeck** [comment]
Thank you for your report, but we don't support RHEL4 inspection.

The main reason is the old command base which doesn't provide the features we need for inspection.

This might change in the future since we are considering inspecting with a binary helper but this is not cut in stone yet.
